SELECT FUNCOPERADOR,
	SUM(DEFEITO) AS DEFEITO,
	CODFUNC
FROM (
		SELECT SUBSTR(CAD.NOMEFUNC, 1, INSTR(CAD.NOMEFUNC, ' ') - 1) || ' ' || (CASE WHEN INSTR(CAD.NOMEFUNC, ' ', INSTR(CAD.NOMEFUNC, ' ') + 1) > 0 THEN SUBSTR(CAD.NOMEFUNC, INSTR(CAD.NOMEFUNC, ' ') + 1, INSTR(CAD.NOMEFUNC, ' ', INSTR(CAD.NOMEFUNC, ' ') + 1) - INSTR(CAD.NOMEFUNC, ' ') - 1) ELSE ' ' END)  AS FUNCOPERADOR,
			CAD.CODFUNC,
			(NVL(SUM(APO.MINSERIDO),0) +
			NVL(SUM(APO.FALTANDO),0) +
			NVL(SUM(APO.INVERTIDO),0) +
			NVL(SUM(APO.TROCADO),0) +
			NVL(SUM(APO.QUEIMADO),0) +
			NVL(SUM(APO.CURTO),0) +
			NVL(SUM(APO.SOLDAFRIA),0) +
			NVL(SUM(APO.DEFEITOMP),0) +
			NVL(SUM(APO.CHICOTE),0) +
			NVL(SUM(APO.DISPLAY),0) +
			NVL(SUM(APO.AJUTENSAO),0) +
			NVL(SUM(APO.ACORRENTE),0) +
			NVL(SUM(APO.LED),0) +
			NVL(SUM(APO.CONSUMO),0) +
			NVL(SUM(APO.CORRENTE),0) +
			NVL(SUM(APO.PROGRAMACAO),0) +
			NVL(SUM(APO.OUTROSDEFEITOS),0) +
			NVL(SUM(APO.ADESIVOTROC),0) +
			NVL(SUM(APO.ADESIVOTORT),0) +
			NVL(SUM(APO.GABARRANHADO),0) +
			NVL(SUM(APO.GABAMASSADO),0) +
			NVL(SUM(APO.TAMPATROCA),0) +
			NVL(SUM(APO.TAMPAAMASS),0)) AS DEFEITO
		FROM AD_APOQLD APO
			INNER JOIN TFPFUN CAD ON APO.FUNCOPERADOR2 = CAD.CODFUNC
		WHERE APO.DTAPO >= :P_PERIODO.INI
			AND APO.DTAPO <= :P_PERIODO.FIN		
		GROUP BY SUBSTR(CAD.NOMEFUNC, 1, INSTR(CAD.NOMEFUNC, ' ') - 1) || ' ' || (CASE WHEN INSTR(CAD.NOMEFUNC, ' ', INSTR(CAD.NOMEFUNC, ' ') + 1) > 0 THEN SUBSTR(CAD.NOMEFUNC, INSTR(CAD.NOMEFUNC, ' ') + 1, INSTR(CAD.NOMEFUNC, ' ', INSTR(CAD.NOMEFUNC, ' ') + 1) - INSTR(CAD.NOMEFUNC, ' ') - 1) ELSE ' ' END) ,
			CAD.CODFUNC
		UNION ALL
		SELECT SUBSTR(CAD.NOMEFUNC, 1, INSTR(CAD.NOMEFUNC, ' ') - 1) || ' ' || (CASE WHEN INSTR(CAD.NOMEFUNC, ' ', INSTR(CAD.NOMEFUNC, ' ') + 1) > 0 THEN SUBSTR(CAD.NOMEFUNC, INSTR(CAD.NOMEFUNC, ' ') + 1, INSTR(CAD.NOMEFUNC, ' ', INSTR(CAD.NOMEFUNC, ' ') + 1) - INSTR(CAD.NOMEFUNC, ' ') - 1) ELSE ' ' END) AS FUNCOPERADOR,
			CAD.CODFUNC,
			(NVL(SUM(APO.MINSERIDO),0) +
			NVL(SUM(APO.FALTANDO),0) +
			NVL(SUM(APO.INVERTIDO),0) +
			NVL(SUM(APO.TROCADO),0) +
			NVL(SUM(APO.QUEIMADO),0) +
			NVL(SUM(APO.CURTO),0) +
			NVL(SUM(APO.SOLDAFRIA),0) +
			NVL(SUM(APO.DEFEITOMP),0) +
			NVL(SUM(APO.CHICOTE),0) +
			NVL(SUM(APO.DISPLAY),0) +
			NVL(SUM(APO.AJUTENSAO),0) +
			NVL(SUM(APO.ACORRENTE),0) +
			NVL(SUM(APO.LED),0) +
			NVL(SUM(APO.CONSUMO),0) +
			NVL(SUM(APO.CORRENTE),0) +
			NVL(SUM(APO.PROGRAMACAO),0) +
			NVL(SUM(APO.OUTROSDEFEITOS),0) +
			NVL(SUM(APO.ADESIVOTROC),0) +
			NVL(SUM(APO.ADESIVOTORT),0) +
			NVL(SUM(APO.GABARRANHADO),0) +
			NVL(SUM(APO.GABAMASSADO),0) +
			NVL(SUM(APO.TAMPATROCA),0) +
			NVL(SUM(APO.TAMPAAMASS),0)) AS DEFEITO
		FROM AD_APOQLD APO
			INNER JOIN TFPFUN CAD ON APO.FUNCOPERADOR = CAD.CODFUNC
		WHERE APO.DTAPO >= :P_PERIODO.INI
			AND APO.DTAPO <= :P_PERIODO.FIN
		GROUP BY SUBSTR(CAD.NOMEFUNC, 1, INSTR(CAD.NOMEFUNC, ' ') - 1) || ' ' || (CASE WHEN INSTR(CAD.NOMEFUNC, ' ', INSTR(CAD.NOMEFUNC, ' ') + 1) > 0 THEN SUBSTR(CAD.NOMEFUNC, INSTR(CAD.NOMEFUNC, ' ') + 1, INSTR(CAD.NOMEFUNC, ' ', INSTR(CAD.NOMEFUNC, ' ') + 1) - INSTR(CAD.NOMEFUNC, ' ') - 1) ELSE ' ' END) ,
			CAD.CODFUNC
	)
GROUP BY FUNCOPERADOR, CODFUNC
HAVING SUM(DEFEITO) > 0
ORDER BY DEFEITO DESC