SELECT V.LABEL,
	SUM(V.TOTAL) AS TOTAL
FROM (
	SELECT 'Mal Inserido' AS LABEL,
		(CASE 
			WHEN CAD.SETOR = 'S' THEN 'SOLDA'
			WHEN CAD.SETOR = 'T' THEN 'TESTE'
			WHEN CAD.SETOR = 'I' THEN 'INSERÇÃO'
			WHEN CAD.SETOR = 'D' THEN 'DISPLAY'
			WHEN CAD.SETOR = 'MF' THEN 'MONTAGEM FINAL'
			WHEN CAD.SETOR = 'TF' THEN 'TRANSFORMADOR/INDUTOR'
			WHEN CAD.SETOR = 'C' THEN 'CAPACITOR'
			WHEN CAD.SETOR = 'DP' THEN 'DISSIPADOR'
			WHEN CAD.SETOR = 'IN' THEN 'INSERSORA'
			WHEN CAD.SETOR = '0' THEN 'SEM SETOR' 
		END) AS SETOR,
		NVL(SUM(APO.MINSERIDO),0) AS TOTAL
	FROM AD_APOQLD APO INNER JOIN AD_CADFUNC CAD ON APO.OPERADOR = CAD.IDFUNC OR APO.OPERADOR2 = CAD.IDFUNC
	WHERE APO.DTAPO >= :P_PERIODO.INI AND APO.DTAPO <= :P_PERIODO.FIN AND CAD.SETOR IN :P_SETOR
	GROUP BY CAD.SETOR
	UNION ALL
	SELECT 'Faltando' AS LABEL,
		(CASE 
			WHEN CAD.SETOR = 'S' THEN 'SOLDA'
			WHEN CAD.SETOR = 'T' THEN 'TESTE'
			WHEN CAD.SETOR = 'I' THEN 'INSERÇÃO'
			WHEN CAD.SETOR = 'D' THEN 'DISPLAY'
			WHEN CAD.SETOR = 'MF' THEN 'MONTAGEM FINAL'
			WHEN CAD.SETOR = 'TF' THEN 'TRANSFORMADOR/INDUTOR'
			WHEN CAD.SETOR = 'C' THEN 'CAPACITOR'
			WHEN CAD.SETOR = 'DP' THEN 'DISSIPADOR'
			WHEN CAD.SETOR = 'IN' THEN 'INSERSORA'
			WHEN CAD.SETOR = '0' THEN 'SEM SETOR' 
		END) AS SETOR,
		NVL(SUM(APO.FALTANDO),0) AS TOTAL
	FROM AD_APOQLD APO INNER JOIN AD_CADFUNC CAD ON APO.OPERADOR = CAD.IDFUNC OR APO.OPERADOR2 = CAD.IDFUNC
	WHERE APO.DTAPO >= :P_PERIODO.INI AND APO.DTAPO <= :P_PERIODO.FIN AND CAD.SETOR IN :P_SETOR
	GROUP BY CAD.SETOR
	UNION ALL
	SELECT 'Invertido' AS LABEL,
		(CASE 
			WHEN CAD.SETOR = 'S' THEN 'SOLDA'
			WHEN CAD.SETOR = 'T' THEN 'TESTE'
			WHEN CAD.SETOR = 'I' THEN 'INSERÇÃO'
			WHEN CAD.SETOR = 'D' THEN 'DISPLAY'
			WHEN CAD.SETOR = 'MF' THEN 'MONTAGEM FINAL'
			WHEN CAD.SETOR = 'TF' THEN 'TRANSFORMADOR/INDUTOR'
			WHEN CAD.SETOR = 'C' THEN 'CAPACITOR'
			WHEN CAD.SETOR = 'DP' THEN 'DISSIPADOR'
			WHEN CAD.SETOR = 'IN' THEN 'INSERSORA'
			WHEN CAD.SETOR = '0' THEN 'SEM SETOR' 
		END) AS SETOR,
		NVL(SUM(APO.INVERTIDO),0) AS TOTAL
	FROM AD_APOQLD APO INNER JOIN AD_CADFUNC CAD ON APO.OPERADOR = CAD.IDFUNC OR APO.OPERADOR2 = CAD.IDFUNC
	WHERE APO.DTAPO >= :P_PERIODO.INI AND APO.DTAPO <= :P_PERIODO.FIN AND CAD.SETOR IN :P_SETOR
	GROUP BY CAD.SETOR
	UNION ALL
	SELECT 'Trocado' AS LABEL,
		(CASE 
			WHEN CAD.SETOR = 'S' THEN 'SOLDA'
			WHEN CAD.SETOR = 'T' THEN 'TESTE'
			WHEN CAD.SETOR = 'I' THEN 'INSERÇÃO'
			WHEN CAD.SETOR = 'D' THEN 'DISPLAY'
			WHEN CAD.SETOR = 'MF' THEN 'MONTAGEM FINAL'
			WHEN CAD.SETOR = 'TF' THEN 'TRANSFORMADOR/INDUTOR'
			WHEN CAD.SETOR = 'C' THEN 'CAPACITOR'
			WHEN CAD.SETOR = 'DP' THEN 'DISSIPADOR'
			WHEN CAD.SETOR = 'IN' THEN 'INSERSORA'
			WHEN CAD.SETOR = '0' THEN 'SEM SETOR' 
		END) AS SETOR,
		NVL(SUM(APO.TROCADO),0) AS TOTAL
	FROM AD_APOQLD APO INNER JOIN AD_CADFUNC CAD ON APO.OPERADOR = CAD.IDFUNC OR APO.OPERADOR2 = CAD.IDFUNC
	WHERE APO.DTAPO >= :P_PERIODO.INI AND APO.DTAPO <= :P_PERIODO.FIN AND CAD.SETOR IN :P_SETOR
	GROUP BY CAD.SETOR
	UNION ALL
	SELECT 'Queimado' AS LABEL,
		(CASE 
			WHEN CAD.SETOR = 'S' THEN 'SOLDA'
			WHEN CAD.SETOR = 'T' THEN 'TESTE'
			WHEN CAD.SETOR = 'I' THEN 'INSERÇÃO'
			WHEN CAD.SETOR = 'D' THEN 'DISPLAY'
			WHEN CAD.SETOR = 'MF' THEN 'MONTAGEM FINAL'
			WHEN CAD.SETOR = 'TF' THEN 'TRANSFORMADOR/INDUTOR'
			WHEN CAD.SETOR = 'C' THEN 'CAPACITOR'
			WHEN CAD.SETOR = 'DP' THEN 'DISSIPADOR'
			WHEN CAD.SETOR = 'IN' THEN 'INSERSORA'
			WHEN CAD.SETOR = '0' THEN 'SEM SETOR' 
		END) AS SETOR,
		NVL(SUM(APO.QUEIMADO),0) AS TOTAL
	FROM AD_APOQLD APO INNER JOIN AD_CADFUNC CAD ON APO.OPERADOR = CAD.IDFUNC OR APO.OPERADOR2 = CAD.IDFUNC
	WHERE APO.DTAPO >= :P_PERIODO.INI AND APO.DTAPO <= :P_PERIODO.FIN AND CAD.SETOR IN :P_SETOR
	GROUP BY CAD.SETOR
	UNION ALL
	SELECT 'Curto' AS LABEL,
		(CASE 
			WHEN CAD.SETOR = 'S' THEN 'SOLDA'
			WHEN CAD.SETOR = 'T' THEN 'TESTE'
			WHEN CAD.SETOR = 'I' THEN 'INSERÇÃO'
			WHEN CAD.SETOR = 'D' THEN 'DISPLAY'
			WHEN CAD.SETOR = 'MF' THEN 'MONTAGEM FINAL'
			WHEN CAD.SETOR = 'TF' THEN 'TRANSFORMADOR/INDUTOR'
			WHEN CAD.SETOR = 'C' THEN 'CAPACITOR'
			WHEN CAD.SETOR = 'DP' THEN 'DISSIPADOR'
			WHEN CAD.SETOR = 'IN' THEN 'INSERSORA'
			WHEN CAD.SETOR = '0' THEN 'SEM SETOR' 
		END) AS SETOR,
		NVL(SUM(APO.CURTO),0) AS TOTAL
	FROM AD_APOQLD APO INNER JOIN AD_CADFUNC CAD ON APO.OPERADOR = CAD.IDFUNC OR APO.OPERADOR2 = CAD.IDFUNC
	WHERE APO.DTAPO >= :P_PERIODO.INI AND APO.DTAPO <= :P_PERIODO.FIN AND CAD.SETOR IN :P_SETOR
	GROUP BY CAD.SETOR
	UNION ALL
	SELECT 'Solda Fria' AS LABEL,
		(CASE 
			WHEN CAD.SETOR = 'S' THEN 'SOLDA'
			WHEN CAD.SETOR = 'T' THEN 'TESTE'
			WHEN CAD.SETOR = 'I' THEN 'INSERÇÃO'
			WHEN CAD.SETOR = 'D' THEN 'DISPLAY'
			WHEN CAD.SETOR = 'MF' THEN 'MONTAGEM FINAL'
			WHEN CAD.SETOR = 'TF' THEN 'TRANSFORMADOR/INDUTOR'
			WHEN CAD.SETOR = 'C' THEN 'CAPACITOR'
			WHEN CAD.SETOR = 'DP' THEN 'DISSIPADOR'
			WHEN CAD.SETOR = 'IN' THEN 'INSERSORA'
			WHEN CAD.SETOR = '0' THEN 'SEM SETOR' 
		END) AS SETOR,
		NVL(SUM(APO.SOLDAFRIA),0) AS TOTAL
	FROM AD_APOQLD APO INNER JOIN AD_CADFUNC CAD ON APO.OPERADOR = CAD.IDFUNC OR APO.OPERADOR2 = CAD.IDFUNC
	WHERE APO.DTAPO >= :P_PERIODO.INI AND APO.DTAPO <= :P_PERIODO.FIN AND CAD.SETOR IN :P_SETOR
	GROUP BY CAD.SETOR
	UNION ALL
	SELECT 'Defeito de MP' AS LABEL,
		(CASE 
			WHEN CAD.SETOR = 'S' THEN 'SOLDA'
			WHEN CAD.SETOR = 'T' THEN 'TESTE'
			WHEN CAD.SETOR = 'I' THEN 'INSERÇÃO'
			WHEN CAD.SETOR = 'D' THEN 'DISPLAY'
			WHEN CAD.SETOR = 'MF' THEN 'MONTAGEM FINAL'
			WHEN CAD.SETOR = 'TF' THEN 'TRANSFORMADOR/INDUTOR'
			WHEN CAD.SETOR = 'C' THEN 'CAPACITOR'
			WHEN CAD.SETOR = 'DP' THEN 'DISSIPADOR'
			WHEN CAD.SETOR = 'IN' THEN 'INSERSORA'
			WHEN CAD.SETOR = '0' THEN 'SEM SETOR' 
		END) AS SETOR,
		NVL(SUM(APO.DEFEITOMP),0) AS TOTAL
	FROM AD_APOQLD APO INNER JOIN AD_CADFUNC CAD ON APO.OPERADOR = CAD.IDFUNC OR APO.OPERADOR2 = CAD.IDFUNC
	WHERE APO.DTAPO >= :P_PERIODO.INI AND APO.DTAPO <= :P_PERIODO.FIN AND CAD.SETOR IN :P_SETOR
	GROUP BY CAD.SETOR
	UNION ALL
	SELECT 'Chicote' AS LABEL,
		(CASE 
			WHEN CAD.SETOR = 'S' THEN 'SOLDA'
			WHEN CAD.SETOR = 'T' THEN 'TESTE'
			WHEN CAD.SETOR = 'I' THEN 'INSERÇÃO'
			WHEN CAD.SETOR = 'D' THEN 'DISPLAY'
			WHEN CAD.SETOR = 'MF' THEN 'MONTAGEM FINAL'
			WHEN CAD.SETOR = 'TF' THEN 'TRANSFORMADOR/INDUTOR'
			WHEN CAD.SETOR = 'C' THEN 'CAPACITOR'
			WHEN CAD.SETOR = 'DP' THEN 'DISSIPADOR'
			WHEN CAD.SETOR = 'IN' THEN 'INSERSORA'
			WHEN CAD.SETOR = '0' THEN 'SEM SETOR' 
		END) AS SETOR,
		NVL(SUM(APO.CHICOTE),0) AS TOTAL
	FROM AD_APOQLD APO INNER JOIN AD_CADFUNC CAD ON APO.OPERADOR = CAD.IDFUNC OR APO.OPERADOR2 = CAD.IDFUNC
	WHERE APO.DTAPO >= :P_PERIODO.INI AND APO.DTAPO <= :P_PERIODO.FIN AND CAD.SETOR IN :P_SETOR
	GROUP BY CAD.SETOR
	UNION ALL
	SELECT 'Display' AS LABEL,
		(CASE 
			WHEN CAD.SETOR = 'S' THEN 'SOLDA'
			WHEN CAD.SETOR = 'T' THEN 'TESTE'
			WHEN CAD.SETOR = 'I' THEN 'INSERÇÃO'
			WHEN CAD.SETOR = 'D' THEN 'DISPLAY'
			WHEN CAD.SETOR = 'MF' THEN 'MONTAGEM FINAL'
			WHEN CAD.SETOR = 'TF' THEN 'TRANSFORMADOR/INDUTOR'
			WHEN CAD.SETOR = 'C' THEN 'CAPACITOR'
			WHEN CAD.SETOR = 'DP' THEN 'DISSIPADOR'
			WHEN CAD.SETOR = 'IN' THEN 'INSERSORA'
			WHEN CAD.SETOR = '0' THEN 'SEM SETOR' 
		END) AS SETOR,
		NVL(SUM(APO.DISPLAY),0) AS TOTAL
	FROM AD_APOQLD APO INNER JOIN AD_CADFUNC CAD ON APO.OPERADOR = CAD.IDFUNC OR APO.OPERADOR2 = CAD.IDFUNC
	WHERE APO.DTAPO >= :P_PERIODO.INI AND APO.DTAPO <= :P_PERIODO.FIN AND CAD.SETOR IN :P_SETOR
	GROUP BY CAD.SETOR
	UNION ALL
	SELECT 'Ajuste de Tensão' AS LABEL,
		(CASE 
			WHEN CAD.SETOR = 'S' THEN 'SOLDA'
			WHEN CAD.SETOR = 'T' THEN 'TESTE'
			WHEN CAD.SETOR = 'I' THEN 'INSERÇÃO'
			WHEN CAD.SETOR = 'D' THEN 'DISPLAY'
			WHEN CAD.SETOR = 'MF' THEN 'MONTAGEM FINAL'
			WHEN CAD.SETOR = 'TF' THEN 'TRANSFORMADOR/INDUTOR'
			WHEN CAD.SETOR = 'C' THEN 'CAPACITOR'
			WHEN CAD.SETOR = 'DP' THEN 'DISSIPADOR'
			WHEN CAD.SETOR = 'IN' THEN 'INSERSORA'
			WHEN CAD.SETOR = '0' THEN 'SEM SETOR' 
		END) AS SETOR,
		NVL(SUM(APO.AJUTENSAO),0) AS TOTAL
	FROM AD_APOQLD APO INNER JOIN AD_CADFUNC CAD ON APO.OPERADOR = CAD.IDFUNC OR APO.OPERADOR2 = CAD.IDFUNC
	WHERE APO.DTAPO >= :P_PERIODO.INI AND APO.DTAPO <= :P_PERIODO.FIN AND CAD.SETOR IN :P_SETOR
	GROUP BY CAD.SETOR
	UNION ALL
	SELECT 'Ajuste de Corrente' AS LABEL,
		(CASE 
			WHEN CAD.SETOR = 'S' THEN 'SOLDA'
			WHEN CAD.SETOR = 'T' THEN 'TESTE'
			WHEN CAD.SETOR = 'I' THEN 'INSERÇÃO'
			WHEN CAD.SETOR = 'D' THEN 'DISPLAY'
			WHEN CAD.SETOR = 'MF' THEN 'MONTAGEM FINAL'
			WHEN CAD.SETOR = 'TF' THEN 'TRANSFORMADOR/INDUTOR'
			WHEN CAD.SETOR = 'C' THEN 'CAPACITOR'
			WHEN CAD.SETOR = 'DP' THEN 'DISSIPADOR'
			WHEN CAD.SETOR = 'IN' THEN 'INSERSORA'
			WHEN CAD.SETOR = '0' THEN 'SEM SETOR' 
		END) AS SETOR,
		NVL(SUM(APO.ACORRENTE),0) AS TOTAL
	FROM AD_APOQLD APO INNER JOIN AD_CADFUNC CAD ON APO.OPERADOR = CAD.IDFUNC OR APO.OPERADOR2 = CAD.IDFUNC
	WHERE APO.DTAPO >= :P_PERIODO.INI AND APO.DTAPO <= :P_PERIODO.FIN AND CAD.SETOR IN :P_SETOR
	GROUP BY CAD.SETOR
	UNION ALL
	SELECT 'LED' AS LABEL,
		(CASE 
			WHEN CAD.SETOR = 'S' THEN 'SOLDA'
			WHEN CAD.SETOR = 'T' THEN 'TESTE'
			WHEN CAD.SETOR = 'I' THEN 'INSERÇÃO'
			WHEN CAD.SETOR = 'D' THEN 'DISPLAY'
			WHEN CAD.SETOR = 'MF' THEN 'MONTAGEM FINAL'
			WHEN CAD.SETOR = 'TF' THEN 'TRANSFORMADOR/INDUTOR'
			WHEN CAD.SETOR = 'C' THEN 'CAPACITOR'
			WHEN CAD.SETOR = 'DP' THEN 'DISSIPADOR'
			WHEN CAD.SETOR = 'IN' THEN 'INSERSORA'
			WHEN CAD.SETOR = '0' THEN 'SEM SETOR' 
		END) AS SETOR,
		NVL(SUM(APO.LED),0) AS TOTAL
	FROM AD_APOQLD APO INNER JOIN AD_CADFUNC CAD ON APO.OPERADOR = CAD.IDFUNC OR APO.OPERADOR2 = CAD.IDFUNC
	WHERE APO.DTAPO >= :P_PERIODO.INI AND APO.DTAPO <= :P_PERIODO.FIN AND CAD.SETOR IN :P_SETOR
	GROUP BY CAD.SETOR
	UNION ALL
	SELECT 'Consumo' AS LABEL,
		(CASE 
			WHEN CAD.SETOR = 'S' THEN 'SOLDA'
			WHEN CAD.SETOR = 'T' THEN 'TESTE'
			WHEN CAD.SETOR = 'I' THEN 'INSERÇÃO'
			WHEN CAD.SETOR = 'D' THEN 'DISPLAY'
			WHEN CAD.SETOR = 'MF' THEN 'MONTAGEM FINAL'
			WHEN CAD.SETOR = 'TF' THEN 'TRANSFORMADOR/INDUTOR'
			WHEN CAD.SETOR = 'C' THEN 'CAPACITOR'
			WHEN CAD.SETOR = 'DP' THEN 'DISSIPADOR'
			WHEN CAD.SETOR = 'IN' THEN 'INSERSORA'
			WHEN CAD.SETOR = '0' THEN 'SEM SETOR' 
		END) AS SETOR,
		NVL(SUM(APO.CONSUMO),0) AS TOTAL
	FROM AD_APOQLD APO INNER JOIN AD_CADFUNC CAD ON APO.OPERADOR = CAD.IDFUNC OR APO.OPERADOR2 = CAD.IDFUNC
	WHERE APO.DTAPO >= :P_PERIODO.INI AND APO.DTAPO <= :P_PERIODO.FIN AND CAD.SETOR IN :P_SETOR
	GROUP BY CAD.SETOR
	UNION ALL
	SELECT 'Corrente Zerada' AS LABEL,
		(CASE 
			WHEN CAD.SETOR = 'S' THEN 'SOLDA'
			WHEN CAD.SETOR = 'T' THEN 'TESTE'
			WHEN CAD.SETOR = 'I' THEN 'INSERÇÃO'
			WHEN CAD.SETOR = 'D' THEN 'DISPLAY'
			WHEN CAD.SETOR = 'MF' THEN 'MONTAGEM FINAL'
			WHEN CAD.SETOR = 'TF' THEN 'TRANSFORMADOR/INDUTOR'
			WHEN CAD.SETOR = 'C' THEN 'CAPACITOR'
			WHEN CAD.SETOR = 'DP' THEN 'DISSIPADOR'
			WHEN CAD.SETOR = 'IN' THEN 'INSERSORA'
			WHEN CAD.SETOR = '0' THEN 'SEM SETOR' 
		END) AS SETOR,
		NVL(SUM(APO.CORRENTE),0) AS TOTAL
	FROM AD_APOQLD APO INNER JOIN AD_CADFUNC CAD ON APO.OPERADOR = CAD.IDFUNC OR APO.OPERADOR2 = CAD.IDFUNC
	WHERE APO.DTAPO >= :P_PERIODO.INI AND APO.DTAPO <= :P_PERIODO.FIN AND CAD.SETOR IN :P_SETOR
	GROUP BY CAD.SETOR
	UNION ALL
	SELECT 'Não Programa' AS LABEL,
		(CASE 
			WHEN CAD.SETOR = 'S' THEN 'SOLDA'
			WHEN CAD.SETOR = 'T' THEN 'TESTE'
			WHEN CAD.SETOR = 'I' THEN 'INSERÇÃO'
			WHEN CAD.SETOR = 'D' THEN 'DISPLAY'
			WHEN CAD.SETOR = 'MF' THEN 'MONTAGEM FINAL'
			WHEN CAD.SETOR = 'TF' THEN 'TRANSFORMADOR/INDUTOR'
			WHEN CAD.SETOR = 'C' THEN 'CAPACITOR'
			WHEN CAD.SETOR = 'DP' THEN 'DISSIPADOR'
			WHEN CAD.SETOR = 'IN' THEN 'INSERSORA'
			WHEN CAD.SETOR = '0' THEN 'SEM SETOR' 
		END) AS SETOR,
		NVL(SUM(APO.PROGRAMACAO),0) AS TOTAL
	FROM AD_APOQLD APO INNER JOIN AD_CADFUNC CAD ON APO.OPERADOR = CAD.IDFUNC OR APO.OPERADOR2 = CAD.IDFUNC
	WHERE APO.DTAPO >= :P_PERIODO.INI AND APO.DTAPO <= :P_PERIODO.FIN AND CAD.SETOR IN :P_SETOR
	GROUP BY CAD.SETOR
	UNION ALL
	SELECT 'Outros Defeitos' AS LABEL,
		(CASE 
			WHEN CAD.SETOR = 'S' THEN 'SOLDA'
			WHEN CAD.SETOR = 'T' THEN 'TESTE'
			WHEN CAD.SETOR = 'I' THEN 'INSERÇÃO'
			WHEN CAD.SETOR = 'D' THEN 'DISPLAY'
			WHEN CAD.SETOR = 'MF' THEN 'MONTAGEM FINAL'
			WHEN CAD.SETOR = 'TF' THEN 'TRANSFORMADOR/INDUTOR'
			WHEN CAD.SETOR = 'C' THEN 'CAPACITOR'
			WHEN CAD.SETOR = 'DP' THEN 'DISSIPADOR'
			WHEN CAD.SETOR = 'IN' THEN 'INSERSORA'
			WHEN CAD.SETOR = '0' THEN 'SEM SETOR' 
		END) AS SETOR,
		NVL(SUM(APO.OUTROSDEFEITOS),0) AS TOTAL
	FROM AD_APOQLD APO INNER JOIN AD_CADFUNC CAD ON APO.OPERADOR = CAD.IDFUNC OR APO.OPERADOR2 = CAD.IDFUNC
	WHERE APO.DTAPO >= :P_PERIODO.INI AND APO.DTAPO <= :P_PERIODO.FIN AND CAD.SETOR IN :P_SETOR
	GROUP BY CAD.SETOR
	UNION ALL
	SELECT 'Adesivo Trocado' AS LABEL,
		(CASE 
			WHEN CAD.SETOR = 'S' THEN 'SOLDA'
			WHEN CAD.SETOR = 'T' THEN 'TESTE'
			WHEN CAD.SETOR = 'I' THEN 'INSERÇÃO'
			WHEN CAD.SETOR = 'D' THEN 'DISPLAY'
			WHEN CAD.SETOR = 'MF' THEN 'MONTAGEM FINAL'
			WHEN CAD.SETOR = 'TF' THEN 'TRANSFORMADOR/INDUTOR'
			WHEN CAD.SETOR = 'C' THEN 'CAPACITOR'
			WHEN CAD.SETOR = 'DP' THEN 'DISSIPADOR'
			WHEN CAD.SETOR = 'IN' THEN 'INSERSORA'
			WHEN CAD.SETOR = '0' THEN 'SEM SETOR' 
		END) AS SETOR,
		NVL(SUM(APO.ADESIVOTROC),0) AS TOTAL
	FROM AD_APOQLD APO INNER JOIN AD_CADFUNC CAD ON APO.OPERADOR = CAD.IDFUNC OR APO.OPERADOR2 = CAD.IDFUNC
	WHERE APO.DTAPO >= :P_PERIODO.INI AND APO.DTAPO <= :P_PERIODO.FIN AND CAD.SETOR IN :P_SETOR
	GROUP BY CAD.SETOR
	UNION ALL
	SELECT 'Adesivo Torto' AS LABEL,
		(CASE 
			WHEN CAD.SETOR = 'S' THEN 'SOLDA'
			WHEN CAD.SETOR = 'T' THEN 'TESTE'
			WHEN CAD.SETOR = 'I' THEN 'INSERÇÃO'
			WHEN CAD.SETOR = 'D' THEN 'DISPLAY'
			WHEN CAD.SETOR = 'MF' THEN 'MONTAGEM FINAL'
			WHEN CAD.SETOR = 'TF' THEN 'TRANSFORMADOR/INDUTOR'
			WHEN CAD.SETOR = 'C' THEN 'CAPACITOR'
			WHEN CAD.SETOR = 'DP' THEN 'DISSIPADOR'
			WHEN CAD.SETOR = 'IN' THEN 'INSERSORA'
			WHEN CAD.SETOR = '0' THEN 'SEM SETOR' 
		END) AS SETOR,
		NVL(SUM(APO.ADESIVOTORT),0) AS TOTAL
	FROM AD_APOQLD APO INNER JOIN AD_CADFUNC CAD ON APO.OPERADOR = CAD.IDFUNC OR APO.OPERADOR2 = CAD.IDFUNC
	WHERE APO.DTAPO >= :P_PERIODO.INI AND APO.DTAPO <= :P_PERIODO.FIN AND CAD.SETOR IN :P_SETOR
	GROUP BY CAD.SETOR
	UNION ALL
	SELECT 'Gabinete Arranhado' AS LABEL,
		(CASE 
			WHEN CAD.SETOR = 'S' THEN 'SOLDA'
			WHEN CAD.SETOR = 'T' THEN 'TESTE'
			WHEN CAD.SETOR = 'I' THEN 'INSERÇÃO'
			WHEN CAD.SETOR = 'D' THEN 'DISPLAY'
			WHEN CAD.SETOR = 'MF' THEN 'MONTAGEM FINAL'
			WHEN CAD.SETOR = 'TF' THEN 'TRANSFORMADOR/INDUTOR'
			WHEN CAD.SETOR = 'C' THEN 'CAPACITOR'
			WHEN CAD.SETOR = 'DP' THEN 'DISSIPADOR'
			WHEN CAD.SETOR = 'IN' THEN 'INSERSORA'
			WHEN CAD.SETOR = '0' THEN 'SEM SETOR' 
		END) AS SETOR,
		NVL(SUM(APO.GABARRANHADO),0) AS TOTAL
	FROM AD_APOQLD APO INNER JOIN AD_CADFUNC CAD ON APO.OPERADOR = CAD.IDFUNC OR APO.OPERADOR2 = CAD.IDFUNC
	WHERE APO.DTAPO >= :P_PERIODO.INI AND APO.DTAPO <= :P_PERIODO.FIN AND CAD.SETOR IN :P_SETOR
	GROUP BY CAD.SETOR
	UNION ALL
	SELECT 'Gabinete Amassado' AS LABEL,
		(CASE 
			WHEN CAD.SETOR = 'S' THEN 'SOLDA'
			WHEN CAD.SETOR = 'T' THEN 'TESTE'
			WHEN CAD.SETOR = 'I' THEN 'INSERÇÃO'
			WHEN CAD.SETOR = 'D' THEN 'DISPLAY'
			WHEN CAD.SETOR = 'MF' THEN 'MONTAGEM FINAL'
			WHEN CAD.SETOR = 'TF' THEN 'TRANSFORMADOR/INDUTOR'
			WHEN CAD.SETOR = 'C' THEN 'CAPACITOR'
			WHEN CAD.SETOR = 'DP' THEN 'DISSIPADOR'
			WHEN CAD.SETOR = 'IN' THEN 'INSERSORA'
			WHEN CAD.SETOR = '0' THEN 'SEM SETOR' 
		END) AS SETOR,
		NVL(SUM(APO.GABAMASSADO),0) AS TOTAL
	FROM AD_APOQLD APO INNER JOIN AD_CADFUNC CAD ON APO.OPERADOR = CAD.IDFUNC OR APO.OPERADOR2 = CAD.IDFUNC
	WHERE APO.DTAPO >= :P_PERIODO.INI AND APO.DTAPO <= :P_PERIODO.FIN AND CAD.SETOR IN :P_SETOR
	GROUP BY CAD.SETOR
	UNION ALL
	SELECT 'Tampa Trocada' AS LABEL,
		(CASE 
			WHEN CAD.SETOR = 'S' THEN 'SOLDA'
			WHEN CAD.SETOR = 'T' THEN 'TESTE'
			WHEN CAD.SETOR = 'I' THEN 'INSERÇÃO'
			WHEN CAD.SETOR = 'D' THEN 'DISPLAY'
			WHEN CAD.SETOR = 'MF' THEN 'MONTAGEM FINAL'
			WHEN CAD.SETOR = 'TF' THEN 'TRANSFORMADOR/INDUTOR'
			WHEN CAD.SETOR = 'C' THEN 'CAPACITOR'
			WHEN CAD.SETOR = 'DP' THEN 'DISSIPADOR'
			WHEN CAD.SETOR = 'IN' THEN 'INSERSORA'
			WHEN CAD.SETOR = '0' THEN 'SEM SETOR' 
		END) AS SETOR,
		NVL(SUM(APO.TAMPATROCA),0) AS TOTAL
	FROM AD_APOQLD APO INNER JOIN AD_CADFUNC CAD ON APO.OPERADOR = CAD.IDFUNC OR APO.OPERADOR2 = CAD.IDFUNC
	WHERE APO.DTAPO >= :P_PERIODO.INI AND APO.DTAPO <= :P_PERIODO.FIN AND CAD.SETOR IN :P_SETOR
	GROUP BY CAD.SETOR
	UNION ALL
	SELECT 'Tampa Amassada' AS LABEL,
		(CASE 
			WHEN CAD.SETOR = 'S' THEN 'SOLDA'
			WHEN CAD.SETOR = 'T' THEN 'TESTE'
			WHEN CAD.SETOR = 'I' THEN 'INSERÇÃO'
			WHEN CAD.SETOR = 'D' THEN 'DISPLAY'
			WHEN CAD.SETOR = 'MF' THEN 'MONTAGEM FINAL'
			WHEN CAD.SETOR = 'TF' THEN 'TRANSFORMADOR/INDUTOR'
			WHEN CAD.SETOR = 'C' THEN 'CAPACITOR'
			WHEN CAD.SETOR = 'DP' THEN 'DISSIPADOR'
			WHEN CAD.SETOR = 'IN' THEN 'INSERSORA'
			WHEN CAD.SETOR = '0' THEN 'SEM SETOR' 
		END) AS SETOR,
		NVL(SUM(APO.TAMPAAMASS),0) AS TOTAL
	FROM AD_APOQLD APO INNER JOIN AD_CADFUNC CAD ON APO.OPERADOR = CAD.IDFUNC OR APO.OPERADOR2 = CAD.IDFUNC
	WHERE APO.DTAPO >= :P_PERIODO.INI AND APO.DTAPO <= :P_PERIODO.FIN AND CAD.SETOR IN :P_SETOR
	GROUP BY CAD.SETOR
	) V
GROUP BY V.LABEL
HAVING SUM(V.TOTAL) > 0