SELECT ITE.CODPROD,
    PRO.DESCRPROD,
    SER.SERIE,
    CAB.NUMNOTA,
    CAB.DTNEG
FROM TGFITE ITE
    INNER JOIN TGFCAB CAB ON ITE.NUNOTA = CAB.NUNOTA
    INNER JOIN TGFSER SER ON CAB.NUNOTA = SER.NUNOTA AND ITE.CODPROD = SER.CODPROD
    INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD AND PRO.USOPROD = 'V'
WHERE CAB.CODPARC = :P_CODPARC
    AND TRUNC(CAB.DTNEG) >= :P_PERIODO.INI
    AND TRUNC(CAB.DTNEG) <= :P_PERIODO.FIN
    AND ITE.ATUALESTOQUE = -1
    AND SER.ATUALESTOQUE = -1
    AND CAB.TIPMOV = 'V' 
    AND (CAB.CODEMP = 501 OR CAB.STATUSNFE <> 'D')
    AND CAB.CODTIPOPER IN (1100,2200,1111,1190,1124,2202) 