SELECT FIN.DTNEG,
	FIN.CODEMP,
	FIN.DTVENC,
	FIN.NUMNOTA,
	FIN.CODPARC,
	PAR.RAZAOSOCIAL,
	FIN.VLRDESDOB,
	FIN.CODTIPTIT,
	TIT.DESCRTIPTIT,
	FIN.CODNAT,
	NAT.DESCRNAT,
	FIN.DHBAIXA,
	FIN.VLRBAIXA,
	(CASE WHEN FIN.PROVISAO='S' THEN 'Provisões' ELSE 'Reais' END) AS PROVREAL,
	FIN.PROVISAO,
	FIN.DESDOBRAMENTO,
	(CASE WHEN FIN.ORIGEM = 'F' THEN 'FINANCEIRO' WHEN FIN.ORIGEM = 'E' THEN 'ESTOQUE' END) AS ORIGEM,
	CUS.DESCRCENCUS,
	FIN.CODCENCUS,
	V.VLRLIQUIDO
FROM TGFFIN FIN
	INNER JOIN TGFPAR PAR ON FIN.CODPARC = PAR.CODPARC
	INNER JOIN TGFTIT TIT ON FIN.CODTIPTIT = TIT.CODTIPTIT
	INNER JOIN TGFNAT NAT ON FIN.CODNAT = NAT.CODNAT
	INNER JOIN TSIEMP EMP ON FIN.CODEMP = EMP.CODEMP
	INNER JOIN VGFFIN V ON FIN.NUFIN = V.NUFIN
	LEFT JOIN TSICUS CUS ON FIN.CODCENCUS = CUS.CODCENCUS
WHERE FIN.DTVENC >= :P_PERIODO.INI
	AND FIN.DTVENC <= :P_PERIODO.FIN
	AND (:P_CODEMP IS NULL OR FIN.CODEMP = :P_CODEMP)
	AND FIN.DHBAIXA IS NULL
	AND FIN.RECDESP = :P_RECDESP
	AND FIN.CODTIPTIT NOT IN (34)
ORDER BY DTVENC , "PROVREAL", PAR.RAZAOSOCIAL