SELECT T.*,
    T.JANEIRO+T.FEVEREIRO+T.MAR+T.ABRIL+T.MAIO+T.JUNHO+T.JULHO+T.AGOSTO+T.SETEMBRO+T.OUTUBRO+T.NOVEMBRO+T.DEZEMBRO AS TOTAL,
    (SELECT APELIDO FROM TGFVEN WHERE CODVEND = T.CODVEND) AS REPRESENTANTE,
	(SELECT DISTINCT UF.DESCRICAO FROM TSIUFS UF INNER JOIN TSICID C ON UF.CODUF = C.UF WHERE C.CODCID = T.CODCID) AS UF
FROM (SELECT V.CODPARC,
            V.RAZAOSOCIAL,
            SUM(CASE WHEN V.MES = 1 THEN V.VLRNOTA + V.VLROUTROS - V.VLRIPI - V.VLRSUBST - (CASE WHEN V.TIPFRETE = 'S' THEN V.VLRFRETE ELSE 0 END)/* + V.VLROUTROSFRETE */ ELSE 0 END) AS JANEIRO,
            SUM(CASE WHEN V.MES = 2 THEN V.VLRNOTA + V.VLROUTROS - V.VLRIPI - V.VLRSUBST - (CASE WHEN V.TIPFRETE = 'S' THEN V.VLRFRETE ELSE 0 END)/* + V.VLROUTROSFRETE */ ELSE 0 END) AS FEVEREIRO,
            SUM(CASE WHEN V.MES = 3 THEN V.VLRNOTA + V.VLROUTROS - V.VLRIPI - V.VLRSUBST - (CASE WHEN V.TIPFRETE = 'S' THEN V.VLRFRETE ELSE 0 END)/* + V.VLROUTROSFRETE */ ELSE 0 END) AS MAR,
            SUM(CASE WHEN V.MES = 4 THEN V.VLRNOTA + V.VLROUTROS - V.VLRIPI - V.VLRSUBST - (CASE WHEN V.TIPFRETE = 'S' THEN V.VLRFRETE ELSE 0 END)/* + V.VLROUTROSFRETE */ ELSE 0 END) AS ABRIL,
            SUM(CASE WHEN V.MES = 5 THEN V.VLRNOTA + V.VLROUTROS - V.VLRIPI - V.VLRSUBST - (CASE WHEN V.TIPFRETE = 'S' THEN V.VLRFRETE ELSE 0 END)/* + V.VLROUTROSFRETE */ ELSE 0 END) AS MAIO,
            SUM(CASE WHEN V.MES = 6 THEN V.VLRNOTA + V.VLROUTROS - V.VLRIPI - V.VLRSUBST - (CASE WHEN V.TIPFRETE = 'S' THEN V.VLRFRETE ELSE 0 END)/* + V.VLROUTROSFRETE */ ELSE 0 END) AS JUNHO,
            SUM(CASE WHEN V.MES = 7 THEN V.VLRNOTA + V.VLROUTROS - V.VLRIPI - V.VLRSUBST - (CASE WHEN V.TIPFRETE = 'S' THEN V.VLRFRETE ELSE 0 END)/* + V.VLROUTROSFRETE */ ELSE 0 END) AS JULHO,
            SUM(CASE WHEN V.MES = 8 THEN V.VLRNOTA + V.VLROUTROS - V.VLRIPI - V.VLRSUBST - (CASE WHEN V.TIPFRETE = 'S' THEN V.VLRFRETE ELSE 0 END)/* + V.VLROUTROSFRETE */ ELSE 0 END) AS AGOSTO,
            SUM(CASE WHEN V.MES = 9 THEN V.VLRNOTA + V.VLROUTROS - V.VLRIPI - V.VLRSUBST - (CASE WHEN V.TIPFRETE = 'S' THEN V.VLRFRETE ELSE 0 END)/* + V.VLROUTROSFRETE */ ELSE 0 END) AS SETEMBRO,
            SUM(CASE WHEN V.MES = 10 THEN V.VLRNOTA + V.VLROUTROS - V.VLRIPI - V.VLRSUBST - (CASE WHEN V.TIPFRETE = 'S' THEN V.VLRFRETE ELSE 0 END)/* + V.VLROUTROSFRETE */ ELSE 0 END) AS OUTUBRO,
            SUM(CASE WHEN V.MES = 11 THEN V.VLRNOTA + V.VLROUTROS - V.VLRIPI - V.VLRSUBST - (CASE WHEN V.TIPFRETE = 'S' THEN V.VLRFRETE ELSE 0 END)/* + V.VLROUTROSFRETE */ ELSE 0 END) AS NOVEMBRO,
            SUM(CASE WHEN V.MES = 12 THEN V.VLRNOTA + V.VLROUTROS - V.VLRIPI - V.VLRSUBST - (CASE WHEN V.TIPFRETE = 'S' THEN V.VLRFRETE ELSE 0 END)/* + V.VLROUTROSFRETE */ ELSE 0 END) AS DEZEMBRO,
            V.CODVEND,
			V.CODCID,
            V.MATRIZ
        FROM (SELECT PAR.CODPARC,  
                    PAR.RAZAOSOCIAL,
                    EXTRACT(MONTH FROM CAB.DTNEG) AS MES,
                    EXTRACT(YEAR FROM CAB.DTNEG) AS ANO,
                    CAB.TIPFRETE,
                    ROUND(SUM(CAB.VLRNOTA),2) AS VLRNOTA,
                    ROUND(SUM(NVL(CAB.VLROUTROS,0)),2) AS VLROUTROS,
                    ROUND(SUM(NVL(CAB.AD_VLROUTROSFRETE,0)),2) AS VLROUTROSFRETE,
                    ROUND(SUM(CAB.VLRIPI),2) AS VLRIPI,
                    ROUND(SUM(CAB.VLRSUBST),2) AS VLRSUBST,
                    ROUND(SUM(CAB.VLRFRETE),2) AS VLRFRETE,
                    CAB.CODVEND,
					PAR.CODCID,
                    P.CODPARC || '-' || P.RAZAOSOCIAL AS MATRIZ
                FROM TGFPAR PAR
                    LEFT JOIN TGFCAB CAB ON (CAB.CODPARC = PAR.CODPARC AND CAB.TIPMOV = 'V' AND CAB.CODTIPOPER IN (1100,2200,1111,1190,1124,2202) AND EXTRACT(YEAR FROM CAB.DTNEG) = :P_ANO)
					INNER JOIN TGFVEN VEN ON PAR.CODVEND = VEN.CODVEND
                    LEFT JOIN TGFPAR P ON PAR.CODPARCMATRIZ = P.CODPARC
                WHERE (:P_CODPARC IS NULL OR PAR.CODPARC = :P_CODPARC)
					AND VEN.TIPVEND <> 'C'
					AND (:P_CODVEND IS NULL OR CAB.CODVEND = :P_CODVEND)
					AND (:P_CODPARCMATRIZ IS NULL OR P.CODPARC = :P_CODPARCMATRIZ)
                GROUP BY PAR.CODPARC, PAR.RAZAOSOCIAL, EXTRACT(MONTH FROM CAB.DTNEG), EXTRACT(YEAR FROM CAB.DTNEG), CAB.TIPFRETE, CAB.CODVEND, PAR.CODPARC, PAR.CODCID, P.CODPARC, P.RAZAOSOCIAL
                ORDER BY PAR.CODPARC, EXTRACT(YEAR FROM CAB.DTNEG), EXTRACT(MONTH FROM CAB.DTNEG)) V
        GROUP BY V.CODPARC, V.RAZAOSOCIAL, V.CODVEND, V.CODCID, V.MATRIZ
        ORDER BY V.CODPARC) T