SELECT
SUM (   ((  (ITE.VLRTOT)
                    - (CASE WHEN :DESC = 'S' THEN ITE.VLRDESC ELSE 0 END)
                    - (CASE WHEN :REP = 'S' THEN ITE.VLRREPRED ELSE 0 END)
                    + (CASE WHEN :ST = 'S' THEN ITE.VLRSUBST ELSE 0 END)
                    + (CASE WHEN :IPI = 'S' THEN ITE.VLRIPI ELSE 0 END)
                   )
              * CASE WHEN CAB.TIPMOV = 'D' THEN -1 ELSE 1 END) * VCAB.INDITENS
             ) AS VALOR,
TO_CHAR(CAB.DTNEG, 'Mon/YYYY') AS PER,
 TO_CHAR(CAB.DTNEG, 'YYYYMM') AS ORDEM

FROM TGFCAB CAB
, TGFPAR PAR
, TGFITE ITE
, TGFPRO PRO
, TGFTOP TPO
, VGFCAB VCAB
WHERE   (CAB.STATUSNOTA = 'L' OR :STATUSNOTA = 'N')
AND ITE.USOPROD <> 'D'
AND TPO.GOLSINAL = -1
AND VCAB.NUNOTA= CAB.NUNOTA
AND ((TPO.GRUPO IN :TOP))  
AND CAB.DTNEG BETWEEN :PERIODO.INI AND :PERIODO.FIN
AND ((PRO.CODPROD= :PRODUTO) OR (:PRODUTO IS NULL))
AND CAB.CODPARC = PAR.CODPARC
AND CAB.NUNOTA = ITE.NUNOTA
AND ITE.CODPROD = PRO.CODPROD
AND CAB.CODTIPOPER = TPO.CODTIPOPER
AND CAB.DHTIPOPER = TPO.DHALTER
GROUP BY TO_CHAR(CAB.DTNEG, 'Mon/YYYY'),
 TO_CHAR(CAB.DTNEG, 'YYYYMM')

ORDER BY 3