WITH FILTRO_V AS (
    SELECT
        PRO.AD_AGRUPADOR,
        PRO.CODVOL,
        PRO.CODGRUPOPROD,
        GRU.DESCRGRUPOPROD,
        VEN.CODVEND,
        VEN.APELIDO,
        ITE.QTDNEG,
        ITE.VLRTOT,
        ITE.VLRDESC,
        NVL(ITE.AD_VLROUTROS, 0) AS AD_VLROUTROS
    FROM TGFITE ITE
        INNER JOIN TGFCAB CAB ON ITE.NUNOTA = CAB.NUNOTA
        INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
        INNER JOIN TGFGRU GRU ON PRO.CODGRUPOPROD = GRU.CODGRUPOPROD
        INNER JOIN TGFVEN VEN ON CAB.CODVEND = VEN.CODVEND
        INNER JOIN TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC
        INNER JOIN TSICID CID ON PAR.CODCID = CID.CODCID
    WHERE CAB.DTNEG >= TRUNC(:P_PER.INI)
        AND CAB.DTNEG < TRUNC(:P_PER.FIN) + 1
        AND CAB.TIPMOV = 'V'
        AND PRO.USOPROD = 'V'
        AND (:P_GRUPO IS NULL OR GRU.CODGRUPOPROD = :P_GRUPO)
        AND (:P_CODEMP IS NULL OR CAB.CODEMP = :P_CODEMP)
        AND (:P_CODVEND IS NULL OR VEN.CODVEND = :P_CODVEND)
        AND (:P_CODPROD IS NULL OR ITE.CODPROD = :P_CODPROD)
        AND ((:P_CODPARC IS NULL OR CAB.CODPARC = :P_CODPARC) AND (:P_CODPARCMATRIZ IS NULL OR PAR.CODPARCMATRIZ = :P_CODPARCMATRIZ))
        AND (:P_CODUF IS NULL OR CID.UF = :P_CODUF)
        AND CAB.CODTIPOPER IN (1100,2200,1111,1190,1124,2202)
),
TOT AS (
    SELECT
        SUM(ITE.QTDNEG) AS TOTAL_QTD,
        SUM(ITE.VLRTOT - ITE.VLRDESC) + SUM(NVL(ITE.AD_VLROUTROS, 0)) AS TOTAL_VAL
    FROM TGFITE ITE
        INNER JOIN TGFCAB CAB ON ITE.NUNOTA = CAB.NUNOTA
        INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
        INNER JOIN TGFGRU GRU ON PRO.CODGRUPOPROD = GRU.CODGRUPOPROD
        INNER JOIN TGFVEN VEN ON CAB.CODVEND = VEN.CODVEND
    WHERE CAB.DTNEG >= TRUNC(:P_PER.INI)
        AND CAB.DTNEG < TRUNC(:P_PER.FIN) + 1
        AND CAB.TIPMOV = 'V'
        AND PRO.USOPROD = 'V'
        AND (:P_GRUPO IS NULL OR GRU.CODGRUPOPROD = :P_GRUPO)
        AND (:P_CODEMP IS NULL OR CAB.CODEMP = :P_CODEMP)
        AND (:P_CODVEND IS NULL OR VEN.CODVEND = :P_CODVEND)
        AND CAB.CODTIPOPER IN (1100,2200,1111,1190,1124,2202)
)
SELECT
    AD_AGRUPADOR,
    CODVOL,
    SUM(QTDNEG) AS QTD,
    CODGRUPOPROD,
    DESCRGRUPOPROD,
    CODVEND,
    APELIDO,
    (SUM(QTDNEG) / NULLIF(TOT.TOTAL_QTD, 0)) * 100 AS PARTE,
    SUM(VLRTOT - VLRDESC) AS TOTALLIQ,
    SUM(AD_VLROUTROS) AS TOTALOUTROS,
    SUM(VLRTOT - VLRDESC) + SUM(AD_VLROUTROS) AS TOTAL,
    ((SUM(VLRTOT - VLRDESC) + SUM(AD_VLROUTROS)) / NULLIF(TOT.TOTAL_VAL, 0)) * 100 AS PARTEFATURADO
FROM FILTRO_V
    CROSS JOIN TOT
GROUP BY AD_AGRUPADOR, CODVOL, CODGRUPOPROD, DESCRGRUPOPROD, CODVEND, APELIDO
ORDER BY AD_AGRUPADOR

/*=========================================================================================================================================================================================================*/

WITH FILTRO_D AS (
    SELECT
        PRO.AD_AGRUPADOR,
        PRO.CODVOL,
        PRO.CODGRUPOPROD,
        GRU.DESCRGRUPOPROD,
        VEN.CODVEND,
        VEN.APELIDO,
        ITE.QTDNEG,
        ITE.VLRTOT,
        ITE.VLRDESC,
        NVL(ITE.AD_VLROUTROS, 0) AS AD_VLROUTROS
    FROM TGFITE ITE
        INNER JOIN TGFCAB CAB ON ITE.NUNOTA = CAB.NUNOTA
        INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
        INNER JOIN TGFGRU GRU ON PRO.CODGRUPOPROD = GRU.CODGRUPOPROD
        INNER JOIN TGFVEN VEN ON CAB.CODVEND = VEN.CODVEND
        INNER JOIN TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC
        INNER JOIN TSICID CID ON PAR.CODCID = CID.CODCID
    WHERE CAB.DTNEG >= TRUNC(:P_PER.INI)
        AND CAB.DTNEG < TRUNC(:P_PER.FIN) + 1
        AND CAB.TIPMOV = 'D'
        AND PRO.USOPROD = 'V'
        AND (:P_GRUPO IS NULL OR GRU.CODGRUPOPROD = :P_GRUPO)
        AND (:P_CODEMP IS NULL OR CAB.CODEMP = :P_CODEMP)
        AND (:P_CODVEND IS NULL OR VEN.CODVEND = :P_CODVEND)
        AND (:P_CODPROD IS NULL OR ITE.CODPROD = :P_CODPROD)
        AND ((:P_CODPARC IS NULL OR CAB.CODPARC = :P_CODPARC) AND (:P_CODPARCMATRIZ IS NULL OR PAR.CODPARCMATRIZ = :P_CODPARCMATRIZ))
        AND (:P_CODUF IS NULL OR CID.UF = :P_CODUF)
        AND CAB.CODTIPOPER IN (1200,1201,1206,1216,1217,1272,2202)
),
TOT_VRET AS (
    SELECT
        SUM(ITE.QTDNEG) AS TOTAL_QTD,
        SUM(ITE.VLRTOT - ITE.VLRDESC) + SUM(NVL(ITE.AD_VLROUTROS, 0)) AS TOTAL_VAL
    FROM TGFITE ITE
        INNER JOIN TGFCAB CAB ON ITE.NUNOTA = CAB.NUNOTA
        INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
        INNER JOIN TGFGRU GRU ON PRO.CODGRUPOPROD = GRU.CODGRUPOPROD
        INNER JOIN TGFVEN VEN ON CAB.CODVEND = VEN.CODVEND
    WHERE CAB.DTNEG >= TRUNC(:P_PER.INI)
        AND CAB.DTNEG < TRUNC(:P_PER.FIN) + 1
        AND CAB.TIPMOV = 'V'
        AND PRO.USOPROD = 'V'
        AND (:P_GRUPO IS NULL OR GRU.CODGRUPOPROD = :P_GRUPO)
        AND (:P_CODEMP IS NULL OR CAB.CODEMP = :P_CODEMP)
        AND (:P_CODVEND IS NULL OR VEN.CODVEND = :P_CODVEND)
        AND CAB.CODTIPOPER IN (1200,1201,1206,1216,1217,1272,2202)
)
SELECT
    AD_AGRUPADOR,
    CODVOL,
    SUM(QTDNEG) AS QTD,
    CODGRUPOPROD,
    DESCRGRUPOPROD,
    CODVEND,
    APELIDO,
    (SUM(QTDNEG) / NULLIF(TOT_VRET.TOTAL_QTD, 0)) * 100 AS PARTE,
    SUM(VLRTOT - VLRDESC) AS TOTALLIQ,
    SUM(AD_VLROUTROS) AS TOTALOUTROS,
    SUM(VLRTOT - VLRDESC) + SUM(AD_VLROUTROS) AS TOTAL,
    ((SUM(VLRTOT - VLRDESC) + SUM(AD_VLROUTROS)) / NULLIF(TOT_VRET.TOTAL_VAL, 0)) * 100 AS PARTEFATURADO
FROM FILTRO_D
    CROSS JOIN TOT_VRET
GROUP BY AD_AGRUPADOR, CODVOL, CODGRUPOPROD, DESCRGRUPOPROD, CODVEND, APELIDO
ORDER BY AD_AGRUPADOR

/*=========================================================================================================================================================================================================*/

SELECT GRU.CODGRUPOPROD,
    GRU.DESCRGRUPOPROD,
    SUM(ITE.QTDNEG) AS TOTAL
FROM TGFITE ITE
    INNER JOIN TGFCAB CAB ON ITE.NUNOTA = CAB.NUNOTA
    INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
    INNER JOIN TGFGRU GRU ON PRO.CODGRUPOPROD = GRU.CODGRUPOPROD
    INNER JOIN TGFVEN VEN ON CAB.CODVEND = VEN.CODVEND
    INNER JOIN TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC
	INNER JOIN TSICID CID ON PAR.CODCID = CID.CODCID
WHERE CAB.DTNEG >= TRUNC(:P_PER.INI) 
    AND CAB.DTNEG < TRUNC(:P_PER.FIN) + 1
    AND CAB.TIPMOV = 'V' 
    AND PRO.USOPROD = 'V' 
    AND ((GRU.CODGRUPOPROD = :P_GRUPO) OR :P_GRUPO IS NULL) 
    AND ((:P_CODEMP IS NULL) OR (CAB.CODEMP = :P_CODEMP)) 
    AND ((:P_CODVEND IS NULL) OR (VEN.CODVEND = :P_CODVEND)) 
    AND CAB.CODTIPOPER IN (1100,2200,1111,1190,1124,2202) 
    AND ((:P_CODPARC IS NULL OR CAB.CODPARC = :P_CODPARC) AND (:P_CODPARCMATRIZ IS NULL OR PAR.CODPARCMATRIZ = :P_CODPARCMATRIZ))
    AND (:P_CODUF IS NULL OR CID.UF = :P_CODUF)
GROUP BY GRU.CODGRUPOPROD, GRU.DESCRGRUPOPROD

/*=========================================================================================================================================================================================================*/

SELECT PRO.AD_AGRUPADOR,
    SUM(ITE.VLRTOT - ITE.VLRDESC - ITE.VLRREPRED) + SUM(NVL(ITE.AD_VLROUTROS,0)) AS TOTAL
FROM TGFITE ITE
    INNER JOIN TGFCAB CAB ON ITE.NUNOTA = CAB.NUNOTA
    INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
    INNER JOIN TGFGRU GRU ON PRO.CODGRUPOPROD = GRU.CODGRUPOPROD
    INNER JOIN TGFVEN VEN ON CAB.CODVEND = VEN.CODVEND
    INNER JOIN TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC
    INNER JOIN TSICID CID ON PAR.CODCID = CID.CODCID
WHERE CAB.DTNEG >= TRUNC(:P_PER.INI) 
    AND CAB.DTNEG < TRUNC(:P_PER.FIN) + 1
    AND CAB.TIPMOV = 'V' 
    AND PRO.USOPROD = 'V' 
    AND ((GRU.CODGRUPOPROD = :P_GRUPO) OR :P_GRUPO IS NULL) 
    AND ((:P_CODEMP IS NULL) OR (CAB.CODEMP = :P_CODEMP)) 
    AND ((:P_CODVEND IS NULL) OR (VEN.CODVEND = :P_CODVEND)) 
    AND CAB.CODTIPOPER IN (1100,2200,1111,1190,1124,2202) 
    AND ((:P_CODPROD IS NULL) OR (ITE.CODPROD = :P_CODPROD)) 
    AND ((:P_CODPARC IS NULL OR CAB.CODPARC = :P_CODPARC) AND (:P_CODPARCMATRIZ IS NULL OR PAR.CODPARCMATRIZ = :P_CODPARCMATRIZ))
    AND (:P_CODUF IS NULL OR CID.UF = :P_CODUF)
GROUP BY PRO.AD_AGRUPADOR