SELECT CAB.NUNOTA, 
	CAB.CODEMP,
	CAB.NUMNOTA,	
	CAB.CODTIPOPER,
	(SELECT MAX(TOP2.DESCROPER) FROM TGFTOP TOP2 WHERE TOP2.CODTIPOPER = CAB.CODTIPOPER) AS DESCROPER,
	CAB.DTENTSAI,
	CAB.CODPARC,
	PAR.NOMEPARC,
	ITE.CODPROD, 
	PRO.DESCRPROD, 
	PRO.CODVOL, 
	ITE.QTDNEG, 
	(ITE.QTDNEG - ITE.QTDENTREGUE) AS PENDENTE,
	ITE.VLRUNIT,
	(CASE WHEN CAB.CODEMP = 501 
		THEN ITE.VLRUNIT
		WHEN ITE.AD_VLRCHEIOCOM IS NULL 
		THEN ITE.VLRUNIT 
		ELSE (CASE WHEN VOA.CODPROD IS NULL 
				THEN ITE.AD_VLRCHEIOCOM 
				WHEN VOA.DIVIDEMULTIPLICA = 'D' 
				THEN ITE.AD_VLRCHEIOCOM * VOA.QUANTIDADE 
				ELSE ITE.AD_VLRCHEIOCOM / VOA.QUANTIDADE 
				END)
		END) AS VLRCHEIO, 
	NVL(ITE.ALIQICMS,0) AS ALIQICMS,
	NVL(ITE.ALIQIPI,0) AS ALIQIPI,
	NVL(ITE.VLRSUBST,0) AS VLRSUBST,
	USU.NOMEUSU AS INCLUSOR,
	NAT.DESCRNAT,
	PRO.ESTMIN,
    III.VLRIMPOSTO,
    III.VLRDESPADUA,
    IDI.VLRPISIMP,
    IDI.VLRCOFINSIMP
FROM TGFITE ITE
	INNER JOIN TGFCAB CAB ON ITE.NUNOTA = CAB.NUNOTA
	INNER JOIN TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC
	INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
	LEFT JOIN TSIUSU USU ON CAB.CODUSUINC = USU.CODUSU
	INNER JOIN TGFNAT NAT ON CAB.CODNAT = NAT.CODNAT
	INNER JOIN TGFGRU GRU ON PRO.CODGRUPOPROD = GRU.CODGRUPOPROD
	LEFT JOIN TGFVOA VOA ON (VOA.CODPROD = ITE.CODPROD AND VOA.CODVOL = ITE.CODVOL AND ((ITE.CONTROLE IS NULL AND VOA.CONTROLE = ' ') OR (ITE.CONTROLE IS NOT NULL AND ITE.CONTROLE = VOA.CONTROLE)))
    LEFT JOIN TGFIII III ON (III.NUNOTA = ITE.NUNOTA AND III.SEQUENCIA = ITE.SEQUENCIA)
    LEFT JOIN TGFIDI IDI ON (IDI.NUNOTA = ITE.NUNOTA AND IDI.SEQUENCIA = ITE.SEQUENCIA)
WHERE (CAB.CODPARC = :P_CODPARC OR :P_CODPARC IS NULL) 
	AND (ITE.CODPROD = :P_CODPROD OR :P_CODPROD IS NULL) 
	AND (CAB.DTENTSAI >= :P_PERIODO.INI AND CAB.DTENTSAI <= :P_PERIODO.FIN) 
	AND (CAB.TIPMOV IN ('C','D')) 
	AND CAB.STATUSNOTA = 'L' 
	AND (CAB.CODNAT = :P_CODNAT OR :P_CODNAT IS NULL) 
	AND ((SUBSTR(PRO.CODGRUPOPROD,0,4) = SUBSTR(:P_CODGRUPOPROD,0,4)) OR :P_CODGRUPOPROD IS NULL) 
	AND (CAB.CODEMP = :P_CODEMP OR :P_CODEMP IS NULL)
ORDER BY CAB.DTENTSAI, 
	CAB.NUNOTA, 
	CAB.CODEMP, 
	CAB.CODPARC, 
	CAB.NUMNOTA
