/*==============================================================================
  Nome do Script : RELACAO DE ITENS ENTRADAS
  Tipo           : Componente BI — Tabela
  Dashboard      : Movimentação de Estoque - Entradas
  Descrição      : Relação detalhada de itens de entrada (compra/devolução) com
                   valores unitários, impostos, custos e informações do fornecedor.

  Parâmetros     : :P_CODPARC — código do fornecedor (optional)
                   :P_CODPROD — código do produto (optional)
                   :P_PERIODO.INI — data inicial (DATE)
                   :P_PERIODO.FIN — data final (DATE)
                   :P_CODNAT — código da natureza (optional)
                   :P_CODGRUPOPROD — código do grupo de produto (optional)
                   :P_CODEMP — código da empresa (optional)

  Tabelas        : TGFITE, TGFCAB, TGFPAR, TGFPRO, TSIUSU, TGFNAT, TGFGRU, TGFVOA, TGFIII, TGFIDI (principais)

  Autor          : Silvio Vieira
  Cargo          : Analista de Sistemas Sênior
  Empresa        : Spark Eletrônica
  Data de Criação: A DEFINIR
  Última Revisão : Abril/2026 — Padronização de cabeçalho e comentários
==============================================================================*/

SELECT CAB.NUNOTA, 
	CAB.CODEMP,
	CAB.NUMNOTA,	
	CAB.CODTIPOPER,
	(SELECT MAX(TOP2.DESCROPER) FROM TGFTOP TOP2 WHERE TOP2.CODTIPOPER = CAB.CODTIPOPER) AS DESCROPER,
	CAB.DTENTSAI,
	CAB.CODPARC,
	PAR.NOMEPARC,
	ITE.CODPROD, 
	PRO.DESCRPROD, 
	PRO.CODVOL, 
	ITE.QTDNEG, 
	(ITE.QTDNEG - ITE.QTDENTREGUE) AS PENDENTE,
	ITE.VLRUNIT,
	CASE WHEN NVL(ITE.QTDNEG, 0) = 0 THEN 0 ELSE NVL(ITE.VLRIPI, 0) / ITE.QTDNEG END AS VLRIPI,
	CASE WHEN NVL(ITE.QTDNEG, 0) = 0 THEN 0 ELSE NVL(ITE.VLRICMS, 0) / ITE.QTDNEG END AS VLRICMS,
	(CASE WHEN CAB.CODEMP = 501 
		THEN ITE.VLRUNIT
		WHEN ITE.AD_VLRCHEIOCOM IS NULL 
		THEN ITE.VLRUNIT 
		ELSE (CASE WHEN VOA.CODPROD IS NULL 
				THEN ITE.AD_VLRCHEIOCOM 
				WHEN VOA.DIVIDEMULTIPLICA = 'D' 
				THEN ITE.AD_VLRCHEIOCOM * VOA.QUANTIDADE 
				ELSE ITE.AD_VLRCHEIOCOM / VOA.QUANTIDADE 
				END)
		END) AS VLRCHEIO, 
	NVL(ITE.ALIQICMS,0) AS ALIQICMS,
	NVL(ITE.ALIQIPI,0) AS ALIQIPI,
	NVL(ITE.VLRSUBST,0) AS VLRSUBST,
	USU.NOMEUSU AS INCLUSOR,
	NAT.DESCRNAT,
	PRO.ESTMIN,
    III.VLRIMPOSTO / ITE.QTDNEG AS VLRIMPOSTO,
    III.VLRDESPADUA / ITE.QTDNEG AS VLRDESPADUA,
    IDI.VLRPISIMP / ITE.QTDNEG AS VLRPISIMP,
    IDI.VLRCOFINSIMP / ITE.QTDNEG AS VLRCOFINSIMP
FROM TGFITE ITE
	INNER JOIN TGFCAB CAB ON ITE.NUNOTA = CAB.NUNOTA
	INNER JOIN TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC
	INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
	LEFT JOIN TSIUSU USU ON CAB.CODUSUINC = USU.CODUSU
	INNER JOIN TGFNAT NAT ON CAB.CODNAT = NAT.CODNAT
	INNER JOIN TGFGRU GRU ON PRO.CODGRUPOPROD = GRU.CODGRUPOPROD
	LEFT JOIN TGFVOA VOA ON (VOA.CODPROD = ITE.CODPROD AND VOA.CODVOL = ITE.CODVOL AND ((ITE.CONTROLE IS NULL AND VOA.CONTROLE = ' ') OR (ITE.CONTROLE IS NOT NULL AND ITE.CONTROLE = VOA.CONTROLE)))
    LEFT JOIN TGFIII III ON (III.NUNOTA = ITE.NUNOTA AND III.SEQUENCIA = ITE.SEQUENCIA)
    LEFT JOIN TGFIDI IDI ON (IDI.NUNOTA = ITE.NUNOTA AND IDI.SEQUENCIA = ITE.SEQUENCIA)
WHERE (CAB.CODPARC = :P_CODPARC OR :P_CODPARC IS NULL) 
	AND (ITE.CODPROD = :P_CODPROD OR :P_CODPROD IS NULL) 
	AND (CAB.DTENTSAI >= :P_PERIODO.INI AND CAB.DTENTSAI <= :P_PERIODO.FIN) 
	AND (CAB.TIPMOV IN ('C','D')) 
	AND CAB.STATUSNOTA = 'L' 
	AND (CAB.CODNAT = :P_CODNAT OR :P_CODNAT IS NULL) 
	AND ((SUBSTR(PRO.CODGRUPOPROD,0,4) = SUBSTR(:P_CODGRUPOPROD,0,4)) OR :P_CODGRUPOPROD IS NULL) 
	AND (CAB.CODEMP = :P_CODEMP OR :P_CODEMP IS NULL)
ORDER BY CAB.DTENTSAI, 
	CAB.NUNOTA, 
	CAB.CODEMP, 
	CAB.CODPARC, 
	CAB.NUMNOTA
