/*==============================================================================
  Nome do Script : RELACAO DE COMPRAS-PRODUTO POR PREVISAO DE ENTREGA
  Tipo           : Componente BI — Tabela
  Dashboard      : Gestão de Compras e Fornecedores
  Descrição      : Relação de itens de compra por produto, volume e fornecedor
                   com quantidades agrupadas por mês de previsão de entrega.

  Parâmetros     : :P_ANO — ano de referência (NUMBER)
                   :P_CODPROD — código do produto (optional)
                   :P_CODPARC — código do fornecedor (optional)
                   :P_CODGRUPOPROD — código do grupo de produto (optional)

  Tabelas        : TGFITE, TGFCAB, TGFPRO, TGFPAR (principais)

  Autor          : Silvio Vieira
  Cargo          : Analista de Sistemas Sênior
  Empresa        : Spark Eletrônica
  Data de Criação: A DEFINIR
  Última Revisão : Abril/2026 — Padronização de cabeçalho e comentários
==============================================================================*/

SELECT V.CODPROD,
	V.DESCRPROD,
	V.CODVOL,
	SUM(CASE WHEN V.MES = 1 THEN V.QTDNEG ELSE 0 END) AS JANEIRO,
	SUM(CASE WHEN V.MES = 2 THEN V.QTDNEG ELSE 0 END) AS FEVEREIRO,
	SUM(CASE WHEN V.MES = 3 THEN V.QTDNEG ELSE 0 END) AS MAR,
	SUM(CASE WHEN V.MES = 4 THEN V.QTDNEG ELSE 0 END) AS ABRIL,
	SUM(CASE WHEN V.MES = 5 THEN V.QTDNEG ELSE 0 END) AS MAIO,
	SUM(CASE WHEN V.MES = 6 THEN V.QTDNEG ELSE 0 END) AS JUNHO,
	SUM(CASE WHEN V.MES = 7 THEN V.QTDNEG ELSE 0 END) AS JULHO,
	SUM(CASE WHEN V.MES = 8 THEN V.QTDNEG ELSE 0 END) AS AGOSTO,
	SUM(CASE WHEN V.MES = 9 THEN V.QTDNEG ELSE 0 END) AS SETEMBRO,
	SUM(CASE WHEN V.MES = 10 THEN V.QTDNEG ELSE 0 END) AS OUTUBRO,
	SUM(CASE WHEN V.MES = 11 THEN V.QTDNEG ELSE 0 END) AS NOVEMBRO,
	SUM(CASE WHEN V.MES = 12 THEN V.QTDNEG ELSE 0 END) AS DEZEMBRO,
	V.RAZAOSOCIAL
FROM (
	SELECT ITE.CODPROD,
		PRO.DESCRPROD,
		ITE.CODVOL, 
		SUM((ITE.QTDNEG - ITE.QTDENTREGUE)) AS QTDNEG, 
		EXTRACT(MONTH FROM CAB.DTPREVENT) AS MES,
		EXTRACT(YEAR FROM CAB.DTPREVENT) AS ANO,
		PAR.CODPARC || '-' || PAR.RAZAOSOCIAL AS RAZAOSOCIAL
	FROM TGFITE ITE
		INNER JOIN TGFCAB CAB ON (ITE.NUNOTA = CAB.NUNOTA AND CAB.STATUSNOTA = 'L')
		INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
		INNER JOIN TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC
	WHERE (:P_CODPROD IS NULL OR ITE.CODPROD = :P_CODPROD)
		AND (:P_CODPARC IS NULL OR CAB.CODPARC = :P_CODPARC)
		AND CAB.TIPMOV = 'O'
		AND CAB.DTPREVENT IS NOT NULL
		AND CAB.PENDENTE = 'S'
		AND ITE.PENDENTE = 'S'
		AND (ITE.QTDNEG - ITE.QTDENTREGUE) > 0
		AND (:P_CODGRUPOPROD IS NULL OR PRO.CODGRUPOPROD = :P_CODGRUPOPROD)
	GROUP BY ITE.CODPROD,
		PRO.DESCRPROD,
		ITE.CODVOL,
		EXTRACT(MONTH FROM CAB.DTPREVENT),
		EXTRACT(YEAR FROM CAB.DTPREVENT),
		PAR.CODPARC || '-' || PAR.RAZAOSOCIAL
	ORDER BY ITE.CODPROD
	) V
WHERE V.ANO = :P_ANO
GROUP BY V.CODPROD,
	V.DESCRPROD,
	V.CODVOL,
	V.RAZAOSOCIAL
ORDER BY V.CODPROD