SELECT DISTINCT CAB.NUMNOTA,
	MAX(ITE.CODCFO) AS CFOP,
	CAB.DTNEG,
	PAR.CODPARC || ' - ' || PAR.RAZAOSOCIAL AS PARCEIRO,
	UFS.UF,
	SUM(ITE.VLRTOT - ITE.VLRDESC) AS VLRNOTA,
    CAB.VLRIPI,
    CAB.VLRFRETE,
    NVL(CAB.AD_VLROUTROSFRETE,0) AS AD_VLROUTROSFRETE,
    NVL(CAB.VLROUTROS,0) AS VLROUTROS,
    CAB.VLRNOTA + NVL(CAB.AD_VLROUTROSFRETE,0) + NVL(CAB.VLROUTROS,0) AS VLR_TOTAL,
	SUM(ITE.QTDNEG) AS QUANTIDADE,
	NVL(CAB.AD_RESULTADO,0) AS RESULTADO,
    CAB.VLRSUBST,
	(CASE WHEN CAB.AD_RESULTADO > 0 THEN (CAB.AD_RESULTADO / (CAB.VLRNOTA + NVL(CAB.VLROUTROS,0)))*100 ELSE 0 END) AS PERCENTUAL
FROM TGFCAB CAB
	INNER JOIN TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA	
	INNER JOIN TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC
	INNER JOIN TSICID CID ON PAR.CODCID = CID.CODCID
	INNER JOIN TSIUFS UFS ON CID.UF = UFS.CODUF
WHERE (:P_CODPARC IS NULL OR CAB.CODPARC = :P_CODPARC)
	AND CAB.DTNEG >= :P_PERIODO.INI
	AND CAB.DTNEG <= :P_PERIODO.FIN
	AND CAB.STATUSNOTA = 'L'
	AND CAB.CODTIPOPER IN (SELECT T.CODTIPOPER FROM TGFTOP T WHERE T.GRUPO = 'Vendas')
	AND (:P_CODEMP IS NULL OR CAB.CODEMP = :P_CODEMP)
GROUP BY CAB.NUMNOTA,
	CAB.DTNEG,
	PAR.CODPARC || ' - ' || PAR.RAZAOSOCIAL,
	UFS.UF,
    CAB.VLRIPI,
    CAB.VLRFRETE,
    CAB.AD_VLROUTROSFRETE,
    NVL(CAB.VLROUTROS,0),
    CAB.VLRNOTA + NVL(CAB.AD_VLROUTROSFRETE,0) + NVL(CAB.VLROUTROS,0),
	NVL(CAB.AD_RESULTADO,0),
    CAB.VLRSUBST,
	(CASE WHEN CAB.AD_RESULTADO > 0 THEN (CAB.AD_RESULTADO / (CAB.VLRNOTA + NVL(CAB.VLROUTROS,0)))*100 ELSE 0 END)