WITH DIN_AGG AS (
    SELECT DIN.NUNOTA,
           DIN.SEQUENCIA,
           SUM(CASE WHEN DIN.CODIMP = 6 AND DIN.CODINC = 3 THEN NVL(DIN.BASE,0) ELSE 0 END) AS DIN_BASE_IMP6,
           SUM(CASE WHEN DIN.CODIMP = 3 AND DIN.CODINC = 3 THEN NVL(DIN.VALOR,0) ELSE 0 END) AS DIN_VALOR_IMP3,
           SUM(CASE WHEN DIN.CODIMP = 2 AND DIN.CODINC = 3 THEN NVL(DIN.VALOR,0) ELSE 0 END) AS DIN_VALOR_IMP2
    FROM TGFDIN DIN
    GROUP BY DIN.NUNOTA, DIN.SEQUENCIA
)
SELECT CAB.NUNOTA,
       CAB.CODEMP,
       CAB.NUMNOTA,
       MAX(ITE.CODCFO) AS CFOP,
       CAB.DTNEG,
       PAR.NOMEPARC,
       UFS.UF,
       CAB.VLRNOTA,
       CAB.AD_RESULTADO,
       ROUND(SUM(
           NVL(ITE.VLRTOT,0)
         - NVL(ITE.VLRDESC,0)
         - NVL(ITE.VLRREPRED,0)
         + NVL(ITE.VLRIPI,0)
         + NVL(ITE.VLRSUBST,0)
         + NVL(DA.DIN_BASE_IMP6,0)
         + NVL(DA.DIN_VALOR_IMP3,0)
         + NVL(DA.DIN_VALOR_IMP2,0)
         + NVL(ITE.AD_VLROUTROS,0)
       ),2) + NVL(MAX(CAB.AD_VLROUTROSFRETE),0) AS TOTAL,
       SUM(ITE.QTDNEG) AS QTD
FROM TGFCAB CAB
  INNER JOIN TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA
  LEFT JOIN DIN_AGG DA ON DA.NUNOTA = CAB.NUNOTA AND DA.SEQUENCIA = ITE.SEQUENCIA
  INNER JOIN TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC
  INNER JOIN TSICID CID ON CID.CODCID = PAR.CODCID
  INNER JOIN TSIUFS UFS ON CID.UF = UFS.CODUF
WHERE TRUNC(CAB.DTNEG) >= :P_PERIODO.INI
  AND TRUNC(CAB.DTNEG) <= :P_PERIODO.FIN
  AND CAB.TIPMOV = 'V'
  AND CAB.CODTIPOPER IN (1100,2200,1111,1190,1124,2202)
  AND (:P_CODEMP IS NULL OR CAB.CODEMP = :P_CODEMP)
  AND CAB.STATUSNFE <> 'D'
GROUP BY
    CAB.NUNOTA,
    CAB.CODEMP,
    CAB.NUMNOTA,
    CAB.DTNEG,
    PAR.NOMEPARC,
    CAB.VLRNOTA,
    UFS.UF,
    CAB.AD_RESULTADO
ORDER BY CAB.NUMNOTA