SELECT 
    F.NUNOTA,
    C.TIPMOV,
    P.RAZAOSOCIAL,
    C.CODNAT AS CODNAT_CAB,
    NC.DESCRNAT AS DESCRNAT_CAB,
    F.CODNAT AS CODNAT_FIN,
    NF.DESCRNAT AS DESCRNAT_FIN
FROM 
    TGFCAB C
    INNER JOIN TGFPAR P ON C.CODPARC = P.CODPARC
    INNER JOIN TGFFIN F ON F.NUNOTA = C.NUNOTA AND C.CODEMP = F.CODEMP
    LEFT JOIN TGFNAT NC ON NC.CODNAT = C.CODNAT
    LEFT JOIN TGFNAT NF ON NF.CODNAT = F.CODNAT
WHERE 
    F.CODTIPTIT NOT IN (34, 35, 36, 15)
    AND F.CODTIPOPER NOT IN (1300)
    AND F.CODNAT <> C.CODNAT
    AND C.DTNEG >= :P_PERIODO.INI 
    AND C.DTNEG <= :P_PERIODO.FIN
