SELECT 
     SUM(CASE WHEN TAB.STATUS = 'A VENCER' THEN TAB.CONTAGEM ELSE 0 END) AS VENCER_QTD
    ,SUM(CASE WHEN TAB.STATUS = 'A VENCER' THEN TAB.TOTAL ELSE 0 END) AS VENCER_TOT
    ,SUM(CASE WHEN TAB.STATUS = 'VENCIDO' THEN TAB.TOTAL ELSE 0 END) AS VENCIDO_TOT
    ,SUM(CASE WHEN TAB.STATUS = 'VENCIDO' THEN TAB.CONTAGEM ELSE 0 END) AS VENCIDO_QTD
    ,SUM(CASE WHEN TAB.STATUS = 'BOLETO EM CARTORIO' THEN TAB.TOTAL ELSE 0 END) AS CARTORIO_TOT
    ,SUM(CASE WHEN TAB.STATUS = 'BOLETO EM CARTORIO' THEN TAB.CONTAGEM ELSE 0 END) AS CARTORIO_QTD
FROM (
/*********BOLETO EM ABERTO****/
SELECT 
    'A VENCER' AS STATUS
    ,COUNT(0) AS CONTAGEM
    ,SUM(F.VLRLIQUIDO) AS TOTAL

FROM TGFFIN FIN 

 INNER JOIN TSICTA CTA 
    ON CTA.CODCTABCOINT = FIN.CODCTABCOINT

 INNER JOIN VGFFIN F
    ON F.NUFIN = FIN.NUFIN

WHERE FIN.DHBAIXA IS NULL 
 AND  FIN.RECDESP = 1
 AND  FIN.PROVISAO = 'N'
 AND  FIN.CODTIPTIT = 4
 AND  FIN.DTVENC >= TRUNC(SYSDATE)
 AND  FIN.NOSSONUM IS NOT NULL
 AND  FIN.DTNEG <= TRUNC(SYSDATE) - 1



GROUP BY FIN.CODCTABCOINT
        ,CTA.DESCRICAO
/*********BOLETO VENCIDO****/
UNION ALL 

SELECT 

     'VENCIDO' AS STATUS
    ,COUNT(0) AS CONTAGEM
    ,SUM(F.VLRLIQUIDO) AS TOTAL
FROM TGFFIN FIN 

 INNER JOIN TSICTA CTA 
    ON CTA.CODCTABCOINT = FIN.CODCTABCOINT

 INNER JOIN VGFFIN F
    ON F.NUFIN = FIN.NUFIN

WHERE FIN.DHBAIXA IS NULL 
 AND  FIN.RECDESP = 1
 AND  FIN.PROVISAO = 'N'
 AND  FIN.CODTIPTIT = 4
 AND  FIN.DTVENC < TRUNC(SYSDATE)
 AND  FIN.NOSSONUM IS NOT NULL



GROUP BY FIN.CODCTABCOINT
        ,CTA.DESCRICAO
UNION ALL 
/*********BOLETO EM CARTORIO****/
SELECT 
     'BOLETO EM CARTORIO' AS STATUS
    ,COUNT(0) AS CONTAGEM
    ,SUM(F.VLRLIQUIDO) AS TOTAL
FROM TGFFIN FIN 

 INNER JOIN TSICTA CTA 
    ON CTA.CODCTABCOINT = FIN.CODCTABCOINT

 INNER JOIN VGFFIN F
    ON F.NUFIN = FIN.NUFIN

WHERE FIN.DHBAIXA IS NULL 
 AND  FIN.RECDESP = 1
 AND  FIN.PROVISAO = 'N'
 AND  FIN.CODTIPTIT = 48
 AND  FIN.DTVENC < TRUNC(SYSDATE)
 AND  FIN.NOSSONUM IS NOT NULL



GROUP BY FIN.CODCTABCOINT
        ,CTA.DESCRICAO

ORDER BY 1
) TAB