create or replace FUNCTION OBTEM_TOTAIS_MRP(P_NUMPS NUMBER, P_CODPRODPA  NUMBER , P_CODPRODMP NUMBER,P_TIPO VARCHAR2)
RETURN FLOAT
IS
	P_VALOR FLOAT;
BEGIN
   
/* OBJETIVO:  BUSCAR VALORES  META PA, QTDE PRODUZIDA PA, SALDO A PRODUZIR PA, NECESSIDADE MP/MRP, NECESSIDADE COMPRA MP/MRP, ESTOQUE DISPONÍVEL MP

P_TIPO:  
M-META PA ;
P - PRODUCAO PA;
S - SALDO PRODUZIR PA
N - NECESSIDADE MP NO MRP FILTRADO
NA - NECESSIDADE 
C - NECESSIDADE COMPRA MP NO MRP FILTRADO
E - ESTOQUE DISPONÍVEL MP
O - Ordem/Pedido de Compra

S- RETORNA O SALDO A PRODUZIR 
CASO O SALDO SEJA NEGATIVO SIGNIFICA QUE FOI PRODUZIDO ACIMA DA META, DESTA FORMA NÃO DEVE INFLUENCIAR NO CÁLCULO DE MPS A COMPRAR
O SALDO VAI FICAR SEMPRE ACUMULANDO OS PERIODOS ANTERIROES ATÉ QUE SEJA GERADO ORDEM DO MPS DO MÊS QUE FICOU DEVENDO A ORDEM DE PRODUÇAÕ,
FOI PREVISTO A MARCAÇÃO PARA INDICAR QUE O ITEM NÃO SERÁ MAIS PRODUZIDO ATRAVÉS DO CAMPO QTDE REDUÇÃO META DA TELA DE METAS PRODUCAO SPARK DESCONSIDERANDO ASSIM NO PLANO ANTERIOR, 
FAZENDO COM QUE O SALDO A PRODUZIR FIQUE ZERO

P, M - RETORNA A QTDE PRODUZIDADA NO MÊS DO MPR INFORMADO = 'P'
       RETORNA A QTDE META NO MÊS DO MRP INFORMADO = 'M'
	   
N - RETORNA A NECESSIDADE DO MP NO MRP FILTRADO, INDEPENDENTE DE SALDO ESTOQUE, PEDIDO DE COMPRA

NA - RETORNA A NECESSIDADE DO MP  DOS PLANOS ANTERIORES  AO MRP FILTRADO, INDEPENDENTE DE SALDO ESTOQUE, PEDIDO DE COMPRA

O - TOTAL DA MP EM PEDIDO DE COMPRA, CONFIRMADO E PENDENTE, DEDUZINDO ENTREGAS PARCIAIS. NÃO CONSIDERO FILTRO POR DATA, TRAZ TUDO EM ABERTO, SE NÃO FOR CONSIDERAR PRECISA MARCAR COMO NÃO PENDENTE O PEDIDO OU ITEM 

*/

	IF P_TIPO ='E' AND P_CODPRODMP > 0 THEN
		BEGIN
			SELECT SUM(E.ESTOQUE-E.RESERVADO) INTO P_VALOR
			FROM TGFEST E 
			WHERE CODLOCAL = 101
				AND E.CODPROD = P_CODPRODMP;
			EXCEPTION WHEN NO_DATA_FOUND THEN P_VALOR := 0;
		END; 
	END IF;
	
	IF P_TIPO = 'S' THEN
		BEGIN
			SELECT SALDO INTO P_VALOR 
			FROM (SELECT SUM(SALDO) AS SALDO FROM VGFSALDOMRP WHERE CODPROD = P_CODPRODPA AND DTREF < (SELECT TRUNC(DTINICMPS,'MM') FROM TPRMPS WHERE NUMPS = P_NUMPS)) D;
			EXCEPTION WHEN NO_DATA_FOUND THEN P_VALOR := 0;
		END;
	END IF;  
	
	IF P_TIPO IN ('P','M') THEN 
		BEGIN
			SELECT SUM(CASE WHEN P_TIPO = 'P' THEN QTDPRODUZIR ELSE QTDPREV END) INTO P_VALOR 
			FROM VGFSALDOMRP 
			WHERE CODPROD = P_CODPRODPA
				AND DTREF = (SELECT TRUNC(DTINICMPS,'MM') FROM TPRMPS WHERE NUMPS = P_NUMPS);
			EXCEPTION WHEN NO_DATA_FOUND THEN P_VALOR := 0;
		END;
	END IF; 
	
	IF P_TIPO = 'N' THEN 
		BEGIN 
			SELECT SUM(LMP.QTDMISTURA*NVL(I.QTDPRODUZIRLIQ,0)) INTO P_VALOR
			FROM TPRMPS MPS 
				INNER JOIN TPRIMPS I ON (MPS.NUMPS = I.NUMPS),
				TPRPRC PRC,
				TPRLPA LPA,
				TPRLMP LMP,
				TPRATV ATV,
				TPROEST EST,
				TGFPRO PRO
				LEFT JOIN TGFPAR PAR ON (PAR.CODPARC = PRO.CODPARCFORN)
			WHERE PRC.IDPROC = I.IDPROC
				AND I.CODPROD = LPA.CODPRODPA
				AND LPA.CODPRODPA = LMP.CODPRODPA
				AND LMP.CODPRODMP = PRO.CODPROD
				AND I.IDPROC = ATV.IDPROC
				AND EST.IDEFX = ATV.IDEFX
				AND LMP.IDEFX = ATV.IDEFX
				AND LPA.IDPROC = I.IDPROC
				AND EST.TIPOITENS='PA'
				AND MPS.NUMPS = P_NUMPS
				AND LMP.CODPRODMP = P_CODPRODMP
				AND LMP.CODPRODPA = CASE WHEN P_CODPRODPA = 0 THEN LMP.CODPRODPA ELSE P_CODPRODPA END
			GROUP BY LMP.CODPRODMP,
				PRO.DESCRPROD,
				PRO.CODVOL,
				NVL(PRO.AGRUPCOMPMINIMO,PRO.AGRUPMIN),
				PRO.CODPARCFORN,PAR.NOMEPARC
			HAVING SUM(LMP.QTDMISTURA * I.QTDPRODUZIRLIQ) > 0;
			EXCEPTION WHEN NO_DATA_FOUND THEN P_VALOR := 0;
		END ;
	END IF;   
	
	IF P_TIPO = 'NA' THEN
	BEGIN
			SELECT SUM(LMP.QTDMISTURA * NVL(SAL.SALDO,0)) INTO P_VALOR
			FROM TPRMPS MPS
				INNER JOIN TPRIMPS I ON MPS.NUMPS = I.NUMPS AND MPS.NUMPS = P_NUMPS
				INNER JOIN VGFSALDOMRP SAL ON (SAL.CODPROD = I.CODPROD)
				INNER JOIN TPRPRC PRC ON PRC.IDPROC = I.IDPROC
				INNER JOIN TPRLPA LPA ON I.CODPROD = LPA.CODPRODPA
				INNER JOIN TPRLMP LMP ON LPA.CODPRODPA = LMP.CODPRODPA AND LPA.IDPROC = I.IDPROC AND LMP.CODPRODMP = P_CODPRODMP
				INNER JOIN TPRATV ATV ON I.IDPROC = ATV.IDPROC AND LMP.IDEFX = ATV.IDEFX
				INNER JOIN TPROEST EST ON EST.IDEFX = ATV.IDEFX AND EST.TIPOITENS= 'PA'
				INNER JOIN TGFPRO PRO ON LMP.CODPRODMP = PRO.CODPROD
				LEFT JOIN TGFPAR PAR ON (PAR.CODPARC = PRO.CODPARCFORN)
			WHERE LMP.CODPRODPA = (CASE WHEN NVL(P_CODPRODPA,0) = 0 THEN LMP.CODPRODPA ELSE P_CODPRODPA END)
				AND SAL.DTREF < (SELECT TRUNC(MPS2.DTINICMPS,'MM') FROM TPRMPS MPS2 WHERE MPS2.NUMPS = P_NUMPS)
			GROUP BY LMP.CODPRODMP,
				PRO.DESCRPROD,
				PRO.CODVOL,
				NVL(PRO.AGRUPCOMPMINIMO,PRO.AGRUPMIN),
				PRO.CODPARCFORN,
				PAR.NOMEPARC
			HAVING SUM(LMP.QTDMISTURA * SAL.SALDO) > 0;
			EXCEPTION WHEN NO_DATA_FOUND THEN P_VALOR := 0;
		END ;
	END IF;
	
	IF P_TIPO IN ('O') THEN
		BEGIN
			SELECT SUM(I.QTDNEG-I.QTDENTREGUE) INTO P_VALOR FROM TGFCAB C INNER JOIN TGFITE I ON (C.NUNOTA = I.NUNOTA)
				INNER JOIN TGFTOP TPO ON (TPO.CODTIPOPER = C.CODTIPOPER AND TPO.DHALTER = C.DHTIPOPER)
			WHERE UPPER(TPO.GRUPO)='PEDIDO COMPRA' 
				AND C.STATUSNOTA='L'
				AND I.PENDENTE='S'
				AND I.CODPROD = P_CODPRODMP;
			EXCEPTION WHEN NO_DATA_FOUND THEN P_VALOR := 0;
		END ;
	END IF;
	
	RETURN NVL(P_VALOR,0);
END;