CREATE OR REPLACE FUNCTION OBTEM_TOTAIS_MRP(
    P_NUMPS NUMBER, 
    P_CODPRODPA NUMBER, 
    P_CODPRODMP NUMBER,
    P_TIPO VARCHAR2
) RETURN FLOAT IS
    P_VALOR FLOAT := 0;
    V_DTINICMPS DATE;
BEGIN
    -- 1. Captura a data do MPS apenas uma vez e armazena em memória
    IF P_TIPO IN ('S', 'P', 'M', 'NA') THEN
        BEGIN
            SELECT TRUNC(DTINICMPS, 'MM') INTO V_DTINICMPS 
            FROM TPRMPS 
            WHERE NUMPS = P_NUMPS;
        EXCEPTION 
            WHEN NO_DATA_FOUND THEN V_DTINICMPS := NULL;
        END;
    END IF;

    -- 2. Uso do ELSIF e simplificação das consultas com NVL
    IF P_TIPO = 'E' AND P_CODPRODMP > 0 THEN
        SELECT NVL(SUM(E.ESTOQUE - E.RESERVADO), 0) INTO P_VALOR
        FROM TGFEST E 
        WHERE CODLOCAL = 101 AND E.CODPROD = P_CODPRODMP;

    ELSIF P_TIPO = 'S' THEN
        SELECT NVL(SUM(SALDO), 0) INTO P_VALOR 
        FROM VGFSALDOMRP 
        WHERE CODPROD = P_CODPRODPA 
          AND DTREF < V_DTINICMPS;

    ELSIF P_TIPO IN ('P', 'M') THEN 
        SELECT NVL(SUM(CASE WHEN P_TIPO = 'P' THEN QTDPRODUZIR ELSE QTDPREV END), 0) INTO P_VALOR 
        FROM VGFSALDOMRP 
        WHERE CODPROD = P_CODPRODPA
          AND DTREF = V_DTINICMPS;

    ELSIF P_TIPO = 'N' THEN 
        -- Removidos os Joins inúteis (TGFPRO, TGFPAR) e a quebra pesada de GROUP BY
        SELECT NVL(SUM(LMP.QTDMISTURA * NVL(I.QTDPRODUZIRLIQ, 0)), 0) INTO P_VALOR
        FROM TPRMPS MPS 
        INNER JOIN TPRIMPS I ON MPS.NUMPS = I.NUMPS
        INNER JOIN TPRLPA LPA ON I.CODPROD = LPA.CODPRODPA AND LPA.IDPROC = I.IDPROC
        INNER JOIN TPRATV ATV ON I.IDPROC = ATV.IDPROC
        INNER JOIN TPRLMP LMP ON LPA.CODPRODPA = LMP.CODPRODPA AND LMP.IDEFX = ATV.IDEFX
        INNER JOIN TPROEST EST ON EST.IDEFX = ATV.IDEFX
        WHERE MPS.NUMPS = P_NUMPS
          AND LMP.CODPRODMP = P_CODPRODMP
          AND EST.TIPOITENS = 'PA'
          AND LMP.CODPRODPA = CASE WHEN P_CODPRODPA = 0 THEN LMP.CODPRODPA ELSE P_CODPRODPA END;

    ELSIF P_TIPO = 'NA' THEN
        -- Mesma otimização de Joins e quebras do bloco 'N'
        SELECT NVL(SUM(LMP.QTDMISTURA * NVL(SAL.SALDO, 0)), 0) INTO P_VALOR
        FROM TPRMPS MPS
        INNER JOIN TPRIMPS I ON MPS.NUMPS = I.NUMPS
        INNER JOIN VGFSALDOMRP SAL ON SAL.CODPROD = I.CODPROD
        INNER JOIN TPRLPA LPA ON I.CODPROD = LPA.CODPRODPA AND LPA.IDPROC = I.IDPROC
        INNER JOIN TPRATV ATV ON I.IDPROC = ATV.IDPROC
        INNER JOIN TPRLMP LMP ON LPA.CODPRODPA = LMP.CODPRODPA AND LMP.IDEFX = ATV.IDEFX
        INNER JOIN TPROEST EST ON EST.IDEFX = ATV.IDEFX
        WHERE MPS.NUMPS = P_NUMPS
          AND LMP.CODPRODMP = P_CODPRODMP
          AND EST.TIPOITENS = 'PA'
          AND SAL.DTREF < V_DTINICMPS
          AND LMP.CODPRODPA = CASE WHEN NVL(P_CODPRODPA, 0) = 0 THEN LMP.CODPRODPA ELSE P_CODPRODPA END;

    ELSIF P_TIPO = 'O' THEN
        SELECT NVL(SUM(I.QTDNEG - I.QTDENTREGUE), 0) INTO P_VALOR 
        FROM TGFCAB C 
        INNER JOIN TGFITE I ON C.NUNOTA = I.NUNOTA
        INNER JOIN TGFTOP TPO ON TPO.CODTIPOPER = C.CODTIPOPER AND TPO.DHALTER = C.DHTIPOPER
        WHERE UPPER(TPO.GRUPO) = 'PEDIDO COMPRA' 
          AND C.STATUSNOTA = 'L'
          AND I.PENDENTE = 'S'
          AND I.CODPROD = P_CODPRODMP;

    END IF;
    
    RETURN P_VALOR;
END;