create or replace PROCEDURE          STP_CRIA_CTACTBCLI_AUDICON AS

P_CODCTACTB   TCBPLA.CODCTACTB%TYPE;
CODEMP   TCBPLA.CODEMP%TYPE;
CTACTB   TCBPLA.CTACTB%TYPE;
GRAU   TCBPLA.GRAU%TYPE;
DESCRCTA   TCBPLA.DESCRCTA%TYPE;
ANALITICA   TCBPLA.ANALITICA%TYPE;
CENCUSOBRIG   TCBPLA.CENCUSOBRIG%TYPE;
CONVSALDOMOEDA   TCBPLA.CONVSALDOMOEDA%TYPE;
DTBASECONVMOEDA   TCBPLA.DTBASECONVMOEDA%TYPE;
CODCTACTBPAI   TCBPLA.CODCTACTBPAI%TYPE;
ATIVA   TCBPLA.ATIVA%TYPE;
BEMORIGINAL   TCBPLA.BEMORIGINAL%TYPE;
BEMRESREAV   TCBPLA.BEMRESREAV%TYPE;
BEMOUTROS   TCBPLA.BEMOUTROS %TYPE;
PODELANCTOMANUAL   TCBPLA.PODELANCTOMANUAL%TYPE;
DTINCLUSAO   TCBPLA.DTINCLUSAO%TYPE;
CODGRUPOCTA   TCBPLA.CODGRUPOCTA%TYPE;
CODCTAREF   TCBPLA.CODCTAREF%TYPE;
RAZAOAUXSPED   TCBPLA.RAZAOAUXSPED%TYPE;
CODCTACTBSUBST   TCBPLA.CODCTACTBSUBST%TYPE;
CODUSU   TCBPLA.CODUSU%TYPE;
DTALTER   TCBPLA.DTALTER%TYPE;
PROJOBRIG   TCBPLA.PROJOBRIG%TYPE;
P_CODPARC    TGFPAR.CODPARC%TYPE;
P_QTDLINHAS   INT;
P_MENSAGEM  VARCHAR2(100);

/* ROTINA CRIADA PELA AUDICON EM 23/01/2026. QUALQUER DÚVIDA FAVOR ACIONAR VIA EMAIL: PABLOFERNANDES@AUDICONCONTADORES.COM.BR*/

CURSOR CONTCTACTB IS
 
    SELECT DISTINCT(FIN.CODPARC), LPAD(FIN.CODPARC,5,1000) AS CODCTACTB, 1 AS CODEMP, 
    '1.1.03.01.001.'||LPAD(FIN.CODPARC,5,0000) AS CTACTB, 
    6 AS GRAU,  REPLACE(REPLACE(SUBSTR(UPPER(NVL(PAR.RAZAOSOCIAL,PAR.NOMEPARC)),1,40),'&','E'),'|',' ') AS DESCRCTA, 'S' AS ANALITICA, 'N' AS CENCUSOBRIG, 'I' AS CONVSALDOMOEDA,
    'U' AS DTBASECONVMOEDA, 169 AS CODCTACTBPAI, 'S' AS ATIVA, 'N' AS BEMORIGINAL, 'N' AS BEMRESREAV,
    'N' AS BEMOUTROS, 'S' AS PODELANCTOMANUAL, TO_CHAR(TRUNC(SYSDATE,'YYYY')) AS DTINCLUSAO, '01' AS CODGRUPOCTA,
    CASE WHEN PAR.IDESTRANGEIRO IS NOT NULL THEN '1.01.02.02.02' ELSE '1.01.02.02.01' END AS CODCTAREF, 'N' AS RAZAOAUXSPED, 0 AS CODCTACTBSUBST, 0 AS CODUSU, TRUNC(SYSDATE) AS DTALTER, 'N' AS PROJOBRIG
    FROM 
    TGFFIN FIN, TGFPAR PAR, TGFTOP TOP, TGFCTB CTB, TGFNAT NAT
    WHERE 
    TOP.CODTIPOPER = FIN.CODTIPOPER 
    AND TOP.DHALTER = FIN.DHTIPOPER
    AND FIN.CODNAT = NAT.CODNAT
    AND TOP.CODTIPOPER = CTB.CODTIPOPER 
    AND CTB.CODCTACTB= 'PARC1'
    AND ((TOP.TIPMOV <> 'I') OR (TOP.TIPMOV='I' AND NVL(NAT.AD_TIPOCTBZ,'N') = 'N'))
    AND FIN.RECDESP = 1
    AND FIN.DTENTSAI>= '01/01/2024'
    AND FIN.CODPARC = PAR.CODPARC
    AND FIN.CODPARC <> 0 
    AND FIN.CODPARC < 99999
    AND PAR.CODCTACTB IS NULL
    AND NOT EXISTS (SELECT 1 FROM TCBPLA PL WHERE PL.CODCTACTB = LPAD(FIN.CODPARC,5,1000))
    ORDER BY FIN.CODPARC;
       
BEGIN

  OPEN CONTCTACTB;
    LOOP
   FETCH CONTCTACTB INTO P_CODPARC, P_CODCTACTB,CODEMP,CTACTB,GRAU,DESCRCTA,ANALITICA,CENCUSOBRIG,CONVSALDOMOEDA,DTBASECONVMOEDA,CODCTACTBPAI,ATIVA,BEMORIGINAL,BEMRESREAV,BEMOUTROS,PODELANCTOMANUAL,DTINCLUSAO,CODGRUPOCTA,CODCTAREF,RAZAOAUXSPED,CODCTACTBSUBST,CODUSU,DTALTER,PROJOBRIG;
    EXIT WHEN CONTCTACTB%NOTFOUND;

     INSERT INTO TCBPLA (CODCTACTB,CODEMP,CTACTB,GRAU,DESCRCTA,ANALITICA,CENCUSOBRIG,CONVSALDOMOEDA,DTBASECONVMOEDA,CODCTACTBPAI,ATIVA,BEMORIGINAL,BEMRESREAV,BEMOUTROS,PODELANCTOMANUAL,DTINCLUSAO,CODGRUPOCTA,CODCTAREF,RAZAOAUXSPED,CODCTACTBSUBST,CODUSU,DTALTER,PROJOBRIG) 
     SELECT P_CODCTACTB,CODEMP,CTACTB,GRAU,DESCRCTA,ANALITICA,CENCUSOBRIG,CONVSALDOMOEDA,DTBASECONVMOEDA,CODCTACTBPAI,ATIVA,BEMORIGINAL,BEMRESREAV,BEMOUTROS,PODELANCTOMANUAL,DTINCLUSAO,CODGRUPOCTA,CODCTAREF,RAZAOAUXSPED,CODCTACTBSUBST,CODUSU,DTALTER,PROJOBRIG FROM DUAL;
     COMMIT;
            
     UPDATE TGFPAR PAR SET PAR.CODCTACTB2 = P_CODCTACTB WHERE PAR.CODPARC = P_CODPARC;
     COMMIT;
    
     INSERT INTO TCBCTR (CODCTACTB,TIPO,CODCTAREF) 
     SELECT P_CODCTACTB,'1',CODCTAREF FROM DUAL;
     COMMIT;
    
   END LOOP;
   CLOSE CONTCTACTB;
   
   

END;