CREATE OR REPLACE TRIGGER TRG_VALIDA_PRAZO_SC
BEFORE INSERT OR UPDATE ON AD_TGSSCP
FOR EACH ROW
BEGIN
  IF :NEW.PRAZO <= TRUNC(SYSDATE) THEN
    RAISE_APPLICATION_ERROR(-20001, 'O prazo de necessidade deve ser maior que a data atual.');
  END IF;
END;
