CREATE OR REPLACE TRIGGER TRG_BLOQUEIA_EDICAO_STATUS_CR
BEFORE UPDATE ON AD_TGSSCP
FOR EACH ROW
BEGIN
  IF :OLD.STATUS = 'CR' THEN
    RAISE_APPLICATION_ERROR(-20010, 'Alterações não são permitidas após o status ser "CR - Compra Realizada".');
  END IF;
END;