CREATE OR REPLACE TRIGGER TRG_ATUALIZA_STATUS_NUNOTA
BEFORE UPDATE ON AD_TGSSCP
FOR EACH ROW
BEGIN
  -- Executa somente se o campo NUNOTA for preenchido e estiver diferente de NULL
  IF :NEW.NUNOTA IS NOT NULL AND :OLD.NUNOTA IS NULL THEN
    :NEW.STATUS := 'CR';
  END IF;
END;