SELECT PAR.CODPARC,
	PAR.NOMEPARC,
	UFS.UF,
	VEN.APELIDO,
	ITE.CODPROD,
	PRO.DESCRPROD,
	CAB.DTNEG,
	ITE.QTDNEG,
	ITE.VLRUNIT*((100-ITE.PERCDESC)/100) AS VLRUNIT,
	NVL(ITE.AD_VLRCHEIO,ITE.VLRUNIT) * ((100-ITE.PERCDESC)/100) AS VLRCHEIODESC,
	TPO.CODTIPOPER,
	TPO.DESCROPER,
	CAB.NUNOTA,
	CAB.NUMNOTA
FROM TGFITE ITE
	INNER JOIN TGFCAB CAB ON ITE.NUNOTA = CAB.NUNOTA
	INNER JOIN TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC
	INNER JOIN TGFTOP TPO ON (TPO.CODTIPOPER = CAB.CODTIPOPER AND TPO.DHALTER = CAB.DHTIPOPER)
	INNER JOIN TSICID CID ON PAR.CODCID = CID.CODCID
	INNER JOIN TSIUFS UFS ON CID.UF = UFS.CODUF
	INNER JOIN TGFVEN VEN ON CAB.CODVEND = VEN.CODVEND
	INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
WHERE ((CAB.DTNEG >= :P_PERIODO.INI) AND (CAB.DTNEG <= :P_PERIODO.FIN))
	AND UPPER(TPO.GRUPO) IN ('VENDAS')
	AND ((:P_CODVEND IS NULL) OR (CAB.CODVEND = :P_CODVEND))
	AND ((:P_CODGRUPOPROD IS NULL) OR (PRO.CODGRUPOPROD = :P_CODGRUPOPROD))
	AND ((:P_UF IS NULL) OR (UFS.UF = :P_UF))
    AND ((:P_CODPARC IS NULL) OR (PAR.CODPARC = :P_CODPARC))
ORDER BY CAB.NUNOTA, ITE.SEQUENCIA