SELECT
	CAB.NUNOTA,
	CAB.NUMNOTA,
	ENE.NOMEEND || ', ' || EMP.NUMEND AS ENDEMP, EMP.RAZAOSOCIAL AS RAZAOSOSCIALEMP,
	CIDE.NOMECID ||' - ' || UFSE.UF AS CIDADEEMP,
	SUBSTR(EMP.CEP,1,2) || '.' || SUBSTR(EMP.CEP,3,3)||'-'|| SUBSTR(EMP.CEP,6,3) AS CEPEMP,
	BAIE.NOMEBAI AS BAIRROEMP,
	EMP.INSCESTAD AS INSCRICAOEMP,
	EMP.CGC,
	EMP.TELEFONE AS TELEFONEEMP,
	EMP.FAX AS FAXEMP,
	EMP.EMAIL AS EMAILEMP,
	EMP.HOMEPAGE,
	CAB.DTNEG,
	TPV.DESCRTIPVENDA,
	CAB.CODPARC,
	PAR.CEP,
	PAR.EMAIL,
	PAR.CODPARC || ' - ' || PAR.RAZAOSOCIAL AS RAZAOSOCIAL,
	ENP.NOMEEND ||', '|| PAR.NUMEND AS ENDPARC,
	CIDP.NOMECID || ' - ' || UFSP.UF AS CIDADEPARC,
	BAIP.NOMEBAI AS BAIRROPARC,
	PAR.CGC_CPF,
	CAB.VLRICMSFCPINT,
	CAB.VLRSTFCPINT,
	PAR.TELEFONE AS TELPARC,
	PAR.FAX AS FAXPARC,
	PAR.IDENTINSCESTAD AS INSCESTADPARC,
	CAB.CODPARCTRANSP,
	(CASE WHEN CAB.CIF_FOB = 'C' THEN 'CIF' WHEN CAB.CIF_FOB = 'S' THEN 'Sem frete' WHEN CAB.CIF_FOB = 'T' THEN 'Terceiros' WHEN CAB.CIF_FOB = 'F' THEN 'FOB' ELSE NULL END) AS CIF_FOB,
	(CASE WHEN CAB.TIPFRETE = 'N' THEN 'Extra Nota' ELSE 'Incluso' END) AS TIPFRETE,
	(CASE WHEN CAB.CODVEND = 0 THEN ' ' ELSE VEN.APELIDO END) AS APELIDO,
	VEN.EMAIL AS EMAILVEND,
	NVL(CAB.OBSERVACAO,' ') AS OBSERVACAO,
	ITE.CODPROD,
	NVL(AD_DESCRPRODOED,PRO.DESCRPROD) AS  DESCRPROD,
	PRO.MARCA,
	ITE.CODVOL,
	ITE.QTDNEG,
	PRO.NCM,
	ITE.CONTROLE,
	ITE.OBSERVACAO AS OBSERVACAOITEM,
	ITE.VLRUNIT*((100-ITE.PERCDESC)/100) AS VLRUNIT,
	ITE.VLRTOT,
	CAB.ORDEMCARGA,
	(ITE.AD_VLRCHEIO - ITE.VLRUNIT) AS VLRDIF,
	ITE.AD_VLROUTROS AS VLROUTROS,
	ROUND(ROUND((ITE.VLRTOT - ITE.VLRDESC + NVL(ITE.AD_VLROUTROS,0)),2) / ITE.QTDNEG,2) AS VLRCHEIODESC,
	ROUND((ITE.VLRTOT - ITE.VLRDESC + NVL(ITE.AD_VLROUTROS,0)),2) AS TOTCHEIO,
	(CAB.VLRNOTA + CAB.VLROUTROS) AS TOTALPED,
	CAB.VLRNOTA,
	NVL(CAB.AD_VLROUTROSFRETE,0) AS AD_VLROUTROSFRETE,
	PART.RAZAOSOCIAL AS TRANSPORTADORA,
	NVL(CAB.VLRIPI,0) AS VALORIPI,
	(CASE WHEN CAB.TIPFRETE = 'N' THEN 0 ELSE NVL(CAB.VLRFRETE,0)+NVL(CAB.AD_VLROUTROSFRETE,0) END) AS VALORFRETE,
	NVL(CAB.VLRSUBST,0) AS VALORST,


   ROUND((ITE.VLRTOT - ITE.VLRDESC + NVL(ITE.AD_VLROUTROS,0)),2) + ITE.VLRIPI + ITE.VLRSUBST AS TOTBRUTO,

	(SELECT T.RAZAOSOCIAL FROM TGFPAR T WHERE T.CODPARC = CAB.CODPARCREDESPACHO) AS REDESPACHO,
	CAB.VLRNOTA + NVL(CAB.VLROUTROS,0) + NVL(CAB.AD_VLROUTROSFRETE,0) AS TOTGER,
	TOP.CODTIPOPER,
	MAX(CASE WHEN NVL(ITE.AD_VLROUTROS,0) <> 0 THEN 1 ELSE 0 END) OVER (PARTITION BY CAB.NUNOTA) AS HAS_VLROUTROS
FROM TGFCAB CAB
	INNER JOIN TSIEMP EMP
        ON CAB.CODEMP = EMP.CODEMP

	INNER JOIN TSIEND ENE
        ON EMP.CODEND = ENE.CODEND

	INNER JOIN TSICID CIDE
        ON EMP.CODCID = CIDE.CODCID

	INNER JOIN TSIUFS UFSE
         ON CIDE.UF = UFSE.CODUF

	INNER JOIN TSIBAI BAIE
        ON EMP.CODBAI = BAIE.CODBAI

	INNER JOIN TGFPAR PAR
        ON CAB.CODPARC = PAR.CODPARC

	INNER JOIN TSIEND ENP
        ON PAR.CODEND = ENP.CODEND

	INNER JOIN TSICID CIDP
        ON PAR.CODCID = CIDP.CODCID

	INNER JOIN TSIUFS UFSP
        ON CIDP.UF = UFSP.CODUF

	INNER JOIN TSIBAI BAIP
        ON PAR.CODBAI = BAIP.CODBAI

	INNER JOIN TGFITE ITE
        ON CAB.NUNOTA = ITE.NUNOTA

	INNER JOIN TGFPRO PRO
        ON ITE.CODPROD = PRO.CODPROD

	LEFT JOIN TGFPAR PART
        ON CAB.CODPARCTRANSP = PART.CODPARC

	LEFT JOIN TGFVEN VEN
        ON CAB.CODVEND = VEN.CODVEND

	INNER JOIN TGFTPV TPV
        ON (CAB.CODTIPVENDA = TPV.CODTIPVENDA
            AND CAB.DHTIPVENDA = TPV.DHALTER
           )
	INNER JOIN TGFTOP TOP
        ON CAB.CODTIPOPER = TOP.CODTIPOPER
        AND CAB.DHTIPOPER = TOP.DHALTER
WHERE CAB.NUNOTA = NVL($P{NUNOTA}, $P{PK_NUNOTA})