SELECT *
FROM TGFIXN 
WHERE STATUS = 0 
AND /* ESSA PARTE DE CÓDIGO É IMBUTIDA NO SANKHYA E ENVIADA JUNTO COM A REGRA*/
TIPO = 'C'
AND NVL(SITUACAOMDE, 0) <> 7
AND DHIMPORT >= TO_DATE('01/01/2026', 'DD/MM/YYYY')
AND SITUACAOCTE = 'A'
AND STATUS IN (0, 2, 4)
AND (SYSDATE - DHEMISS) * 24 > 48
AND EXISTS (
    SELECT 1
    FROM VW_CTE_AUTORIZADOS VW
    WHERE VW.NUARQUIVO = CTE.NUARQUIVO
        VW.CODTIPOPER_NFE = 214
);
