SELECT A.T_CODPROD,
    A.T_DESCRPROD,
    COUNT(A.NUMOS) AS TOTAL
FROM AD_SPKCAE A
WHERE (:P_PERIODO.INI IS NULL OR A.DTCONCLUSAO >= :P_PERIODO.INI)
    AND (:P_PERIODO.FIN IS NULL OR A.DTCONCLUSAO <= :P_PERIODO.FIN)
    AND (:P_CODPARC IS NULL OR A.CODPARC = :P_CODPARC)
GROUP BY A.T_CODPROD, A.T_DESCRPROD
