SELECT IA.CODPROD,
    P.DESCRPROD,
    SUM(IA.QTDMOV) AS TOTAL
FROM AD_SPKICAE IA
    INNER JOIN TGFPRO P ON IA.CODPROD = P.CODPROD
    INNER JOIN AD_SPKCAE A ON IA.NUMOS = A.NUMOS
WHERE (:P_PERIODO.INI IS NULL OR A.DTCONCLUSAO >= :P_PERIODO.INI)
    AND (:P_PERIODO.FIN IS NULL OR A.DTCONCLUSAO <= :P_PERIODO.FIN)
    AND (:P_CODPARC IS NULL OR A.CODPARC = :P_CODPARC)
GROUP BY IA.CODPROD, P.DESCRPROD
