SELECT PROC.IDIPROC,
	IPA.QTDPRODUZIR,
	PRO.DESCRPROD,
	PROC.DHINC,
	IPA.NROLOTE,
	IPA.CODPRODPA,
	PROC.NUMPS,
	PROC.DTPREVENT,
	PRO.COMPLDESC,
	PRO.AD_OBSTECNICA,
	(SELECT LPA.AD_OBSPLANEJA FROM TPRLPA LPA WHERE LPA.CODPRODPA = IPA.CODPRODPA AND LPA.IDPROC = PROC.IDPROC) AS AD_OBSPLANEJA,
    (SELECT RC.VERSAO FROM TPRPRC RC WHERE RC.IDPROC = PROC.IDPROC) AS VERSAO
FROM TPRIPROC PROC
	INNER JOIN TPRIPA IPA ON IPA.IDIPROC = PROC.IDIPROC
	INNER JOIN TGFPRO PRO ON PRO.CODPROD = IPA.CODPRODPA
WHERE NVL(PROC.AD_AGRUPADORIMP,PROC.IDIPROC) IN (SELECT NVL(PR.AD_AGRUPADORIMP,PR.IDIPROC) FROM TPRIPROC PR WHERE PR.IDIPROC= $P{PK_IDIPROC})
ORDER BY PROC.IDIPROC