SELECT COUNT(ASS.NUMOS) AS QTD,
    ASS.CODPARC,
    PRO.DESCRPROD
FROM AD_TGFASS ASS
    LEFT JOIN TGFPAR PAR ON ASS.CODPARC = PAR.CODPARC
    LEFT JOIN TGFPRO PRO ON ASS.T_CODPROD = PRO.CODPROD
WHERE ASS.DTRECEB BETWEEN :P_PERIODO.INI AND :P_PERIODO.FIN
    AND (:P_DTFAB.INI IS NULL OR TRUNC(ASS.T_DTFABRICACAO) >= :P_DTFAB.INI)
    AND (:P_DTFAB.FIN IS NULL OR TRUNC(ASS.T_DTFABRICACAO) <= :P_DTFAB.FIN)
    AND :A_CODPARC = ASS.CODPARC
GROUP BY ASS.CODPARC,
    PRO.DESCRPROD
ORDER BY COUNT(ASS.NUMOS) DESC