SELECT GRU.DESCRGRUPOPROD,
    GRU.CODGRUPOPROD,
    SUM(IAS.QTDMOV) AS QTDMOV
FROM AD_TGFIASS IAS
    INNER JOIN AD_TGFASS ASS ON IAS.NUMOS = ASS.NUMOS
    LEFT JOIN TGFPRO PRO ON IAS.CODPROD = PRO.CODPROD
    LEFT JOIN TGFGRU GRU ON PRO.CODGRUPOPROD = GRU.CODGRUPOPROD
    LEFT JOIN TGFPRO PROPA ON ASS.T_CODPROD = PROPA.CODPROD
    LEFT JOIN TGFGRU GRUPA ON PROPA.CODGRUPOPROD = GRUPA.CODGRUPOPROD
WHERE ASS.DTRECEB BETWEEN :P_PERIODO.INI AND :P_PERIODO.FIN
    AND (:P_DTFAB.INI IS NULL OR TRUNC(ASS.T_DTFABRICACAO) >= :P_DTFAB.INI)
    AND (:P_DTFAB.FIN IS NULL OR TRUNC(ASS.T_DTFABRICACAO) <= :P_DTFAB.FIN)
    AND (:P_CODGRUPOMAPROD IS NULL OR PRO.CODGRUPOPROD = :P_CODGRUPOMAPROD)
    AND (:P_CODGRUPOPROD IS NULL OR PROPA.CODGRUPOPROD = :P_CODGRUPOPROD)
GROUP BY GRU.DESCRGRUPOPROD,
    GRU.CODGRUPOPROD
ORDER BY SUM(IAS.QTDMOV) DESC
