SELECT COUNT(ASS.NUMOS) AS QTD,
    CID.UF AS CODUF,
    UFS.UF AS UF
FROM AD_TGFASS ASS
    INNER JOIN TGFPAR PAR ON ASS.CODPARC = PAR.CODPARC
    LEFT JOIN TSICID CID ON PAR.CODCID = CID.CODCID
    LEFT JOIN TSIUFS UFS ON CID.UF = UFS.CODUF
WHERE ASS.DTRECEB BETWEEN :P_PERIODO.INI AND :P_PERIODO.FIN
    AND (:P_DTFAB.INI IS NULL OR TRUNC(ASS.T_DTFABRICACAO) >= :P_DTFAB.INI)
    AND (:P_DTFAB.FIN IS NULL OR TRUNC(ASS.T_DTFABRICACAO) <= :P_DTFAB.FIN)
GROUP BY UFS.UF,
    CID.UF
ORDER BY COUNT(ASS.NUMOS) DESC