SELECT 
    TO_CHAR(ASS.DTRECEB, 'Month', 'NLS_DATE_LANGUAGE=PORTUGUESE') AS NOME_MES,
    SUM(IAS.QTDMOV) AS QTDMOV
FROM AD_TGFIASS IAS
    INNER JOIN AD_TGFASS ASS ON IAS.NUMOS = ASS.NUMOS
    LEFT JOIN TGFPRO PRO ON IAS.CODPROD = PRO.CODPROD
    LEFT JOIN TGFGRU GRU ON PRO.CODGRUPOPROD = GRU.CODGRUPOPROD
WHERE ASS.DTRECEB BETWEEN :P_PERIODO.INI AND :P_PERIODO.FIN
    AND (:P_DTFAB.INI IS NULL OR TRUNC(ASS.T_DTFABRICACAO) >= :P_DTFAB.INI)
    AND (:P_DTFAB.FIN IS NULL OR TRUNC(ASS.T_DTFABRICACAO) <= :P_DTFAB.FIN)
    AND ((GRU.CODGRUPOPROD = :A_CODGRUPOPROD) OR (PRO.CODPROD = :A_CODGRUPOPROD))

GROUP BY 
    EXTRACT(MONTH FROM ASS.DTRECEB),
    TO_CHAR(ASS.DTRECEB, 'Month', 'NLS_DATE_LANGUAGE=PORTUGUESE')
ORDER BY 
    EXTRACT(MONTH FROM ASS.DTRECEB),
    SUM(IAS.QTDMOV) DESC