create or replace PROCEDURE "SPK_TPRLPA_OBSPLANEJA" (
	P_CODUSU NUMBER,        -- Código do usuário logado
	P_IDSESSAO VARCHAR2,    -- Identificador da execução. Serve para buscar informações dos parâmetros/campos da execução.
	P_QTDLINHAS NUMBER,     -- Informa a quantidade de registros selecionados no momento da execução.
	P_MENSAGEM OUT VARCHAR2 -- Caso seja passada uma mensagem aqui, ela será exibida como uma informação ao usuário.
) AS
	PARAM_MENSAGEM VARCHAR2(4000);
	FIELD_IDPROC NUMBER;
	FIELD_CODPRODPA NUMBER;
	FIELD_CONTROLEPA VARCHAR2(4000);
BEGIN
	-- Os valores informados pelo formulário de parâmetros, podem ser obtidos com as funções:
	--     ACT_INT_PARAM
	--     ACT_DEC_PARAM
	--     ACT_TXT_PARAM
	--     ACT_DTA_PARAM
	-- Estas funções recebem 2 argumentos:
	--     ID DA SESSÃO - Identificador da execução (Obtido através de P_IDSESSAO))
	--     NOME DO PARAMETRO - Determina qual parametro deve se deseja obter.
	PARAM_MENSAGEM := ACT_TXT_PARAM(P_IDSESSAO, 'MENSAGEM');
	FOR I IN 1..P_QTDLINHAS -- Este loop permite obter o valor de campos dos registros envolvidos na execução.
		LOOP                    -- A variável "I" representa o registro corrente.
		-- Para obter o valor dos campos utilize uma das seguintes funções:
		--     ACT_INT_FIELD (Retorna o valor de um campo tipo NUMÉRICO INTEIRO))
		--     ACT_DEC_FIELD (Retorna o valor de um campo tipo NUMÉRICO DECIMAL))
		--     ACT_TXT_FIELD (Retorna o valor de um campo tipo TEXTO),
		--     ACT_DTA_FIELD (Retorna o valor de um campo tipo DATA)
		-- Estas funções recebem 3 argumentos:
		--     ID DA SESSÃO - Identificador da execução (Obtido através do parâmetro P_IDSESSAO))
		--     NÚMERO DA LINHA - Relativo a qual linha selecionada.
		--     NOME DO CAMPO - Determina qual campo deve ser obtido.
			FIELD_IDPROC := ACT_INT_FIELD(P_IDSESSAO, I, 'IDPROC');
			FIELD_CODPRODPA := ACT_INT_FIELD(P_IDSESSAO, I, 'CODPRODPA');
			FIELD_CONTROLEPA := ACT_TXT_FIELD(P_IDSESSAO, I, 'CONTROLEPA');
			
			-- <ESCREVA SEU CÓDIGO AQUI (SERÁ EXECUTADO PARA CADA REGISTRO SELECIONADO)> --
			UPDATE TPRLPA SET AD_OBSPLANEJA = PARAM_MENSAGEM || ' - ' || SYSDATE WHERE CODPRODPA = FIELD_CODPRODPA AND IDPROC = FIELD_IDPROC;
		END LOOP;
		
		P_MENSAGEM := 'Atualização concluída com sucesso.';
END;