create or replace PROCEDURE Stp_ALTCAMOUTROS_SPARK(P_NUNOTA INT, P_SEQUENCIA INT, P_SUCESSO OUT VARCHAR, P_MENSAGEM OUT VARCHAR2, P_CODUSULIB OUT NUMBER)
AS
BEGIN
DECLARE
P_VLROUTROS     FLOAT;
BEGIN

 --DA MESMA FORMA QUE NA ANTERIOR, AQUI TERIA A ROTINA EM SI...

 P_SUCESSO := 'S';

 SELECT ROUND(NVL(SUM(AD_VLROUTROS),0),2) INTO P_VLROUTROS
   FROM TGFITE 
  WHERE NUNOTA = P_NUNOTA;

IF P_VLROUTROS >= 0 THEN

  UPDATE TGFCAB SET VLROUTROS = P_VLROUTROS
  WHERE NUNOTA = P_NUNOTA;

END IF;
-- P_MENSAGEM := 'A REGRA FALHOU DE PROPÓSITO, SÓ PARA TESTAR.';

-- P_CODUSULIB := 0;

END;
END;