create or replace PROCEDURE          STP_COPIALISTAMP_SPARK (
       P_CODUSU NUMBER,        -- Código do usuário logado
       P_IDSESSAO VARCHAR2,    -- Identificador da execução. Serve para buscar informações dos parâmetros/campos da execução.
       P_QTDLINHAS NUMBER,     -- Informa a quantidade de registros selecionados no momento da execução.
       P_MENSAGEM OUT VARCHAR2 -- Caso seja passada uma mensagem aqui, ela será exibida como uma informação ao usuário.
) AS
/*==============================================================================
  Nome do Script : STP_COPIALISTAMP_SPARK
  Tipo           : Stored Procedure (Botão de Ação)
  Descrição      : Copia lista de matérias-primas (TPRLMP, TPRMPA, TPRLPI, TPRTPP)
                   de um processo de manufatura para outro, replicando composição
                   de produto, substitutos, operações e índices de controle de qualidade.

  Parâmetros     : P_CODUSU     — código do usuário logado
                   P_IDSESSAO   — identificador da execução (usado por ACT_TXT_PARAM / ACT_INT_FIELD)
                   P_QTDLINHAS  — quantidade de registros selecionados
                   P_MENSAGEM   — mensagem de retorno ao usuário (OUT)

  Autor          : Silvio Vieira
  Cargo          : Analista de Sistemas Sênior
  Empresa        : Spark Eletrônica
  Data de Criação: [A DEFINIR]
  Última Revisão : Abril/2026 — Padronização de cabeçalho e comentários
==============================================================================*/
       PARAM_CODPRODMPORIG VARCHAR2(4000);
       PARAM_CODPRC NUMBER;
       FIELD_IDPROC NUMBER;
       FIELD_CODPRODPA NUMBER;
       FIELD_CONTROLEPA VARCHAR2(4000);

       P_COUNT INT;
       P_SEQMP INT;
       V_COUNT INT;
       P_SEQMPALT INT;
       P_IDPROCMPORIG TPRLPA.IDPROC%TYPE;
       P_IDEFX TPRLMP.IDEFX%TYPE;
       P_IDPROC INT;

       P_RESULT     INT;

       V_QTDLINHASC INT;

BEGIN

       PARAM_CODPRODMPORIG := ACT_TXT_PARAM(P_IDSESSAO, 'CODPRODMPORIG');
       PARAM_CODPRC := ACT_INT_PARAM(P_IDSESSAO, 'CODPRC');

       FOR I IN 1..P_QTDLINHAS -- Este loop permite obter o valor de campos dos registros envolvidos na execução.
       LOOP                    -- A variável "I" representa o registro corrente.

           FIELD_IDPROC := ACT_INT_FIELD(P_IDSESSAO, I, 'IDPROC');
           FIELD_CODPRODPA := ACT_INT_FIELD(P_IDSESSAO, I, 'CODPRODPA');
           FIELD_CONTROLEPA := ACT_TXT_FIELD(P_IDSESSAO, I, 'CONTROLEPA');


    SELECT MAX(IDPROC) INTO P_IDPROC FROM TPRPRC 
    WHERE CODPRC = PARAM_CODPRC
    AND EXISTS (SELECT 1 FROM TPRLPA WHERE IDPROC = TPRPRC.IDPROC AND CODPRODPA = FIELD_CODPRODPA);


    SELECT DECODE(P_IDPROC,NULL,NVL(MAX(T.IDPROC),0),P_IDPROC)
    INTO P_IDPROCMPORIG 
    FROM TPRATV T INNER JOIN TPRLMP M ON (T.IDEFX = M.IDEFX) 
    WHERE T.IDPROC IN (SELECT MAX(ATV.IDPROC)
                       FROM TPRATV ATV INNER JOIN TPRLMP MP ON (ATV.IDEFX = MP.IDEFX)
                       WHERE MP.CODPRODPA = PARAM_CODPRODMPORIG) 
    AND M.CODPRODPA = PARAM_CODPRODMPORIG;

    IF P_IDPROCMPORIG > 0 THEN

      FOR R IN (SELECT M.IDEFX, M.SEQMP, TIPOUSOMP, CODPRODPA, CONTROLEPA, 
                TIPOCONTROLEMP, CODPRODMP, CONTROLEMP, TIPOQTD, QTDMISTURA, 
                CODVOL, VERIFICAEST, GERAREQUISICAO, CODLOCALORIG, PERCDESVIOINF, 
                PERCDESVIOSUP, CODLOCALBAIXA, FIXAQTDAPO 
                FROM  TPRATV T INNER JOIN TPRLMP M ON (T.IDEFX = M.IDEFX)  
                WHERE  T.IDPROC = P_IDPROCMPORIG 
                AND M.CODPRODPA = PARAM_CODPRODMPORIG
                )
                /*AND CODPRODMP NOT IN (SELECT MP.CODPRODMP
                                      FROM  TPRATV ATV INNER JOIN TPRLMP MP ON (ATV.IDEFX = MP.IDEFX)
                                      WHERE MP.CODPRODPA = FIELD_CODPRODPA
                                      AND MP.CONTROLEPA = FIELD_CONTROLEPA
                                      AND ATV.IDPROC = FIELD_IDPROC))*/

      LOOP

     -- SELECT CODPLP INTO P_CODPLP FROM TPRPRC WHERE IDPROC = FIELD_IDPROC;

     IF NVL(P_IDPROC,FIELD_IDPROC) =  FIELD_IDPROC THEN
     /*
        SELECT-- MAX(M.SEQMP)+1, 
            MAX(M.IDEFX)
        INTO --P_SEQMP, 
        P_IDEFX
         FROM TPRATV T INNER JOIN TPRLMP M ON (T.IDEFX = M.IDEFX)  
        WHERE T.IDPROC = FIELD_IDPROC
          AND M.CODPRODPA = PARAM_CODPRODMPORIG;
      */
        SELECT MAX(M.IDEFX)
        INTO P_IDEFX
        FROM TPRATV T 
        INNER JOIN TPRLMP M ON (T.IDEFX = M.IDEFX)
        INNER JOIN TPREFX EFX ON EFX.IDEFX = T.IDEFX
        WHERE T.IDPROC = FIELD_IDPROC
        AND M.CODPRODPA = PARAM_CODPRODMPORIG
        AND NVL(EFX.DESCRICAO,'APONTAMENTO PA') LIKE '%APONTA%';
     ELSE
      /*
         SELECT-- MAX(M.SEQMP)+1, 
            MAX(M.IDEFX)
        INTO --P_SEQMP, 
        P_IDEFX
         FROM TPRATV T INNER JOIN TPRLMP M ON (T.IDEFX = M.IDEFX)  
        WHERE T.IDPROC = FIELD_IDPROC;
        --  AND M.CODPRODPA = PARAM_CODPRODMPORIG;
        --RAISE_APPLICATION_ERROR(-20101, FIELD_IDPROC);
        */
        SELECT MAX(M.IDEFX)
        INTO P_IDEFX
        FROM TPRATV T 
        INNER JOIN TPRLMP M ON (T.IDEFX = M.IDEFX)
        INNER JOIN TPREFX EFX ON EFX.IDEFX = T.IDEFX
        WHERE T.IDPROC = FIELD_IDPROC
        AND NVL(EFX.DESCRICAO,'APONTAMENTO PA') LIKE '%APONTA%';
     END IF;

         SELECT MAX(SEQMP)+1 INTO P_SEQMP FROM TPRLMP WHERE IDEFX = P_IDEFX;
      --    AND M.CODPRODPA = PARAM_CODPRODMPORIG;

       /* RAISE_APPLICATION_ERROR (
                   -20101,
                       CHR (10)
                    || CHR (10)
                    || '<b>''AQUI! '||FIELD_IDPROC||' '||PARAM_CODPRODMPORIG||' '||P_IDEFX|| '</b>'
                    || CHR (10)
                    || CHR (10));
*/
        INSERT INTO TPRLMP 
        (IDEFX, SEQMP, TIPOUSOMP, CODPRODPA, CONTROLEPA, 
        TIPOCONTROLEMP, CODPRODMP, CONTROLEMP, TIPOQTD, QTDMISTURA, 
        CODVOL, VERIFICAEST, GERAREQUISICAO, CODLOCALORIG, PERCDESVIOINF, 
        PERCDESVIOSUP, CODLOCALBAIXA, FIXAQTDAPO) 
        VALUES
        (P_IDEFX, P_SEQMP, R.TIPOUSOMP, FIELD_CODPRODPA, FIELD_CONTROLEPA, 
        R.TIPOCONTROLEMP, R.CODPRODMP, R.CONTROLEMP, R.TIPOQTD, R.QTDMISTURA, 
        R.CODVOL, R.VERIFICAEST, R.GERAREQUISICAO, R.CODLOCALORIG, R.PERCDESVIOINF, 
        R.PERCDESVIOSUP, R.CODLOCALBAIXA, R.FIXAQTDAPO);

        FOR D IN (SELECT M.IDEFX, SEQMPA, CODPRODPA, CONTROLEPA, CODPRODMP, 
        CONTROLEMP, CODPRODMPALT, CONTROLEMPALT, USOMPA, QTDMISTURA, 
        CODVOL, CONJUNTO
                  FROM  TPRATV T INNER JOIN TPRMPA M ON (T.IDEFX = M.IDEFX)  
                  WHERE  T.IDPROC = P_IDPROCMPORIG 
                  AND M.CODPRODPA = PARAM_CODPRODMPORIG
                  )
                  --AND CODPRODMP NOT IN (SELECT CODPRODMP FROM TPRMPA MP WHERE MP.IDEFX = P_IDEFX  AND MP.CODPRODPA = FIELD_CODPRODPA AND MP.CONTROLEPA = FIELD_CONTROLEPA))
        LOOP
           SELECT MAX(M.SEQMPA)+1 INTO P_SEQMPALT FROM  TPRATV T INNER JOIN TPRMPA M ON (T.IDEFX = M.IDEFX)  
                  WHERE  T.IDPROC = FIELD_IDPROC ;  

        INSERT INTO TPRMPA 
        (IDEFX, SEQMPA, CODPRODPA, CONTROLEPA, CODPRODMP, 
        CONTROLEMP, CODPRODMPALT, CONTROLEMPALT, USOMPA, QTDMISTURA, 
        CODVOL, CONJUNTO)
        VALUES
        (P_IDEFX, P_SEQMPALT, FIELD_CODPRODPA, D.CONTROLEPA,D.CODPRODMP,
        D.CONTROLEMP,D.CODPRODMPALT, D.CONTROLEMPALT, D.USOMPA, D.QTDMISTURA,
        D.CODVOL, D.CONJUNTO) ;

        END LOOP;           
      END LOOP;

      FOR Z IN (SELECT IDPROC, CODPRODPA, CONTROLEPA, CODPRODPI, CONTROLEPI, TIPOPI, TIPOSUBOP, AGUARDARSUBOP, TIPONROLOTE, CONSIDERAQTDEST,REDIMENSIONAPA,REDIMENSIONAPAPERDA
                FROM TPRLPI
                WHERE  IDPROC = P_IDPROCMPORIG 
                AND CODPRODPA = PARAM_CODPRODMPORIG)
      LOOP       
        INSERT INTO TPRLPI 
        (IDPROC, CODPRODPA, CONTROLEPA, CODPRODPI, CONTROLEPI,TIPOPI, TIPOSUBOP, AGUARDARSUBOP, 
        TIPONROLOTE, CONSIDERAQTDEST,REDIMENSIONAPA,REDIMENSIONAPAPERDA)        
        VALUES
        (FIELD_IDPROC, FIELD_CODPRODPA, Z.CONTROLEPA, Z.CODPRODPI, Z.CONTROLEPI, Z.TIPOPI, Z.TIPOSUBOP, Z.AGUARDARSUBOP, 
        Z.TIPONROLOTE, Z.CONSIDERAQTDEST,Z.REDIMENSIONAPA,Z.REDIMENSIONAPAPERDA);
      END LOOP;      

      FOR W IN (SELECT IDPROC, CODPRODPA, CONTROLEPA, CODPRODTAR, QTD, CODVOL, TIPOINDICE, TIPOEXEC
                FROM TPRTPP
                WHERE  IDPROC = P_IDPROCMPORIG 
                AND CODPRODPA = PARAM_CODPRODMPORIG)
      LOOP       
        INSERT INTO TPRTPP 
        (IDPROC, CODPRODPA, CONTROLEPA, CODPRODTAR, QTD, CODVOL, TIPOINDICE, TIPOEXEC)        
        VALUES
        (FIELD_IDPROC, FIELD_CODPRODPA, W.CONTROLEPA, W.CODPRODTAR, W.QTD, W.CODVOL, W.TIPOINDICE, W.TIPOEXEC);
      END LOOP;       

      V_COUNT := 1 ;        

    END IF;

  END LOOP;

  P_MENSAGEM := 'Cópia realizada com sucesso!';
END; 
