create or replace PROCEDURE          STP_LIBERASERIE_SPARK
AS
BEGIN
 FOR X IN (SELECT  CODPROD, SERIE, C.IDIPROC FROM TGFSER S INNER JOIN TGFCAB C ON (S.NUNOTA = C.NUNOTA)
 INNER JOIN TPRIPROC PROC ON (PROC.IDIPROC = C.IDIPROC)
    WHERE  C.CODTIPOPER in (800,1214,1200,1201)
    AND NOT EXISTS (SELECT 1 FROM TGFBAR BAR WHERE BAR.CODPROD = S.CODPROD AND BAR.CODBARRA = S.SERIE)
    AND NOT EXISTS (SELECT SER.SERIE FROM TGFSER SER INNER JOIN TGFCAB CAB ON SER.NUNOTA = CAB.NUNOTA WHERE CAB.CODTIPOPER = 512 AND SER.SERIE = S.SERIE)
    )    
        
 LOOP 
 
 /*LIBERA APENAS SERIES QUE EXISTEM NA ORDEM DE PRODUÇÃO QUE ENTROU O PA E FICA NA TGFSER */
 UPDATE TPRSERPA SET LIBERADO = 'S', AD_LIBEXPED ='S' WHERE IDIPROC = X.IDIPROC AND CODPRODPA = X.CODPROD AND SERIEPA = X.SERIE;
 COMMIT;
 
 END LOOP;
 
 
 FOR D IN (SELECT  CODPROD, SERIE, C.IDIPROC FROM TGFSER S INNER JOIN TGFCAB C ON (S.NUNOTA = C.NUNOTA)
     WHERE  C.CODTIPOPER in (800,1214)
    AND EXISTS (SELECT 1 FROM TGFEST EST WHERE EST.CODPROD = S.CODPROD AND EST.CODBARRA = S.SERIE)
    )    
        
 LOOP 
 
 /*LIBERA APENAS SERIES QUE EXISTEM NA ORDEM DE PRODUÇÃO QUE ENTROU O PA E FICA NA TGFSER */
 UPDATE TGFEST SET CODBARRA =NULL WHERE CODPROD = D.CODPROD AND CODBARRA = D.SERIE;
 COMMIT;
 
 END LOOP;
 
 
 
 
END;