create or replace PROCEDURE STP_INTEGRAPEDIDO_AGENDADA AS
    FIELD_NUPED      NUMBER;
    P_CODTIPOPER     NUMBER := 1006;
    P_CODEMP         NUMBER := 2;
    P_MAXNUNOTA      NUMBER;
    P_NUMNOTATOP     NUMBER;
    P_DHTIPOPER      DATE;
    P_NUNOTA         NUMBER;
    P_VLRTOT         NUMBER;
    P_VLRDESC        NUMBER;
    P_CODPARC        NUMBER;
    P_MAXFILA        NUMBER;
    P_OBSERVACAO     VARCHAR2(200);

    CURSOR CUR_PEDIDOS IS
        SELECT NUPED, OBSERVACAO
        FROM AD_TGSCAB
        WHERE NUNOTA IS NULL;

    CURSOR CURSOR_ITENS IS
        SELECT I.IDITEM, I.CODPROD, 'UN', I.QTDNEG, I.VLRUNIT, I.VLRDESC, I.VLRUNITLIQ, I.DESCONTO
        FROM AD_TGSITE I
        WHERE I.NUPED = FIELD_NUPED;

    V_IDITEM         AD_TGSITE.IDITEM%TYPE;
    V_CODPROD        AD_TGSITE.CODPROD%TYPE;
    V_CODVOL         VARCHAR2(2);
    V_QTDNEG         AD_TGSITE.QTDNEG%TYPE;
    V_VLRUNIT        AD_TGSITE.VLRUNIT%TYPE;
    V_VLRDESC        AD_TGSITE.VLRDESC%TYPE;
    V_VLRUNITLIQ     AD_TGSITE.VLRUNITLIQ%TYPE;
    V_DESCONTO       AD_TGSITE.DESCONTO%TYPE;

BEGIN
    OPEN CUR_PEDIDOS;
    LOOP
        FETCH CUR_PEDIDOS INTO FIELD_NUPED, P_OBSERVACAO;
        EXIT WHEN CUR_PEDIDOS%NOTFOUND;

        -- Recupera dados necessários
        SELECT MAX(NUNOTA) + 1 INTO P_MAXNUNOTA FROM TGFCAB;
        SELECT NVL(MAX(ULTCOD) + 1, 0) INTO P_NUMNOTATOP FROM TGFNUM WHERE ARQUIVO LIKE '%1006%';
        SELECT MAX(DHALTER) INTO P_DHTIPOPER FROM TGFTOP WHERE CODTIPOPER = P_CODTIPOPER;
        SELECT NVL(SUM(VLRDESC * QTDNEG),0), NVL(SUM(VLRTOT),0) INTO P_VLRDESC, P_VLRTOT FROM AD_TGSITE WHERE NUPED = FIELD_NUPED;
        SELECT CODPARC INTO P_CODPARC FROM AD_TGSPAR WHERE ID = (SELECT ID FROM AD_TGSCAB WHERE NUPED = FIELD_NUPED);

        -- Inserção no TGFCAB
        INSERT INTO TGFCAB (NUNOTA, CODEMP, CODCENCUS, NUMNOTA, DTNEG,DTMOV, CODEMPNEGOC, CODPARC, RATEADO, CODVEICULO,
            CODTIPOPER, DHTIPOPER, TIPMOV, CODTIPVENDA, DHTIPVENDA, CODVEND, COMISSAO, CODMOEDA, CODOBSPADRAO, VLRSEG,
            VLRICMSSEG, VLRDESTAQUE, VLRJURO, VLRVENDOR, VLROUTROS, VLREMB, VLRICMSEMB, VLRDESCSERV, IPIEMB, TIPIPIEMB,
            VLRDESCTOT, VLRDESCTOTITEM, VLRFRETE, ICMSFRETE, BASEICMSFRETE, TIPFRETE, VLRNOTA, CODPARCTRANSP, QTDVOL,
            PENDENTE, BASEICMS, VLRICMS, BASEIPI, VLRIPI, ISSRETIDO, BASEISS, VLRISS, APROVADO, STATUSNOTA, IRFRETIDO,
            VLRIRF, DTALTER, CODPARCDEST, VLRSUBST, BASESUBSTIT, CODPROJ, NUMCONTRATO, BASEINSS, VLRINSS, VLRREPREDTOT,
            PERCDESC, CODPARCREMETENTE, CODPARCCONSIGNATARIO, CODPARCREDESPACHO, CODNAT, TROCO, CODUSUCOMPRADOR, CIF_FOB,
            OBSERVACAO, CODUSU, CODUSUINC,  AD_CODLOCALDEST) 
        VALUES (P_MAXNUNOTA, P_CODEMP, 30100, P_NUMNOTATOP, SYSDATE,SYSDATE, P_CODEMP, P_CODPARC, 'N', 0, P_CODTIPOPER,
            P_DHTIPOPER, 'P', 128, (SELECT MAX(DHALTER) FROM TGFTPV WHERE CODTIPVENDA = 128), 6, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 'N', 0, P_VLRDESC, 0, 0, 0, 'N', P_VLRTOT, 0,0, 'S', 0, 0, 0, 0, 'N',  0, 0, 'N', 'A', 'S', 0, SYSDATE,
            0, 0, 0, 0, 0 ,0, 0, 0, 0, 0, 0, 0, 101001, 0, 0, 'S', 'VENDA REALIZADA DURANTE AUTOMEC E INTEGRADA VIA SITE ' || P_OBSERVACAO,
            5, 5, NULL);

        -- Atualiza tabela AD_TGSCAB
        UPDATE AD_TGSCAB SET NUNOTA = P_MAXNUNOTA WHERE NUPED = FIELD_NUPED;

        -- Itens do pedido
        OPEN CURSOR_ITENS;
        LOOP
            FETCH CURSOR_ITENS INTO V_IDITEM, V_CODPROD, V_CODVOL, V_QTDNEG, V_VLRUNIT, V_VLRDESC, V_VLRUNITLIQ, V_DESCONTO;
            EXIT WHEN CURSOR_ITENS%NOTFOUND;

            INSERT INTO TGFITE (NUNOTA, SEQUENCIA, CODEMP, CODPROD, CODLOCALORIG, CODCFO, QTDNEG, QTDENTREGUE, QTDCONFERIDA,
                VLRUNIT, VLRCUS, BASEIPI, VLRIPI, BASEICMS, VLRICMS, VLRDESC, BASESUBSTIT, VLRSUBST, PENDENTE, CODVOL, 
                ATUALESTOQUE, RESERVA, STATUSNOTA, CODVEND, CODEXEC, FATURAR, VLRREPRED, VLRDESCBONIF, PERCDESC)
            VALUES (P_MAXNUNOTA, V_IDITEM, P_CODEMP, V_CODPROD, 109, 0, V_QTDNEG, 0, 0, V_VLRUNIT, V_VLRUNIT, 0, 0, 0, 0,
            V_VLRDESC, 0, 0, 'S', V_CODVOL, 1, 'S', 'A', 6, 0, 'S', 0, 0, V_DESCONTO);
				
            INSERT INTO TGFSER (NUNOTA, CODPROD, SEQUENCIA, SERIE, ATUALESTOQUE, CODUSU, DTALTER) 
            SELECT P_MAXNUNOTA, S.CODPROD, V_IDITEM, S.SERIE, 0, 5, SYSDATE
            FROM AD_TGSSER S
            WHERE S.NUPED = FIELD_NUPED AND S.CODPROD = V_CODPROD AND S.STATUS = 'R';
        END LOOP;
        CLOSE CURSOR_ITENS;
        SELECT MAX(CODFILA)+1 INTO P_MAXFILA FROM TMDFMG;
        STP_GRAVA_FILA_BI2(P_MAXFILA,
                'Inclusão de novo pedido AUTOMEC ',
                '<div style="font-family: Arial, sans-serif; color: #333; max-width: 600px; line-height: 1.5;">
                <h2 style="color: #0056b3; border-bottom: 2px solid #0056b3; padding-bottom: 5px;">Novo pedido criado</h2>            
                <p>Um novo pedido vindo foi criado no portal de vendas. Esse pedido foi realizado na AUTOMEC e tem como número único ' || P_MAXNUNOTA || '</p>            
                <p><strong>Data de Criação:</strong> ' || TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI:SS') || '</p>            
                </div>',
                'ti@usinaspark.com.br',
                NULL);
    END LOOP;
    CLOSE CUR_PEDIDOS;
END;