create or replace PROCEDURE STP_IMPRIMIETIQUETA_SPARK (P_NUNOTA FLOAT,
       P_DTIMPRESS TIMESTAMP,
       P_CODPROD FLOAT)
AS
BEGIN
  DECLARE
  P_Notas       VARCHAR2(1);

BEGIN

UPDATE TGFITE SET AD_DHIMPRESSAO=P_DTIMPRESS WHERE CODPROD=P_CODPROD AND NUNOTA=P_NUNOTA;

END;
END;