SELECT * 
FROM (SELECT PRC.CODPRC AS CODIGO,
			PRC.DESCRABREV AS DESCRICAO,
			PROC.IDIPROC AS IDIPROC,
			PROC.DHINST AS DTINICO,
			PROC.DHTERMINO AS DHFINAL,
			PROC.DTPREVENT,
			PROC.NROLOTE,
			IPA.QTDPRODUZIR AS TAMLOTE,
			IPA.QTDPRODUZIR - NVL((SELECT SUM(APA.QTDAPONTADA+APA.QTDPERDA) FROM TPRAPO APO INNER JOIN TPRAPA APA ON (APO.NUAPO = APA.NUAPO) INNER JOIN TPRIATV TV ON (APO.IDIATV = TV.IDIATV) WHERE APO.SITUACAO='C' AND TV.IDIPROC = PROC.IDIPROC	AND TRUNC(APO.DHAPO) BETWEEN :P_DTAPONT.INI AND :P_DTAPONT.FIN),0) AS QTDPRODUZIR,
			NVL((SELECT SUM(APA.QTDAPONTADA) FROM TPRAPO APO INNER JOIN TPRAPA APA ON (APO.NUAPO = APA.NUAPO) INNER JOIN TPRIATV TV ON (APO.IDIATV = TV.IDIATV) WHERE APO.SITUACAO='C' AND TV.IDIPROC = PROC.IDIPROC AND TRUNC(APO.DHAPO) BETWEEN :P_DTAPONT.INI AND :P_DTAPONT.FIN),0) AS QTDAPON,
			NVL((SELECT SUM(APA.QTDPERDA) FROM TPRAPO APO INNER JOIN TPRAPA APA ON (APO.NUAPO = APA.NUAPO) INNER JOIN TPRIATV TV ON (APO.IDIATV = TV.IDIATV) WHERE APO.SITUACAO='C' AND TV.IDIPROC = PROC.IDIPROC AND TRUNC(APO.DHAPO) BETWEEN :P_DTAPONT.INI AND :P_DTAPONT.FIN),0) AS QTDPERDA,
			PRO.CODPROD,
			PRO.DESCRPROD,
			(CASE WHEN PRO.AD_LINHA = 1 THEN 'Linha 1' WHEN PRO.AD_LINHA = 2 THEN 'Linha 2' ELSE 'Linha N/E' END) AS LINHA,
			(SELECT DISTINCT G.DESCRGRUPOPROD FROM TGFGRU G WHERE G.CODGRUPOPROD = PRO.CODGRUPOPROD) AS DESCRGRUPOPROD,
			OPTION_LABEL('TPRIPROC','STATUSPROC',PROC.STATUSPROC) AS STATUSPROD
		FROM TPRIPROC PROC 
			INNER JOIN TPRPRC PRC ON (PROC.IDPROC = PRC.IDPROC)
			INNER JOIN TPRIPA IPA ON (IPA.IDIPROC = PROC.IDIPROC)
			INNER JOIN TGFPRO PRO ON (IPA.CODPRODPA = PRO.CODPROD)
		WHERE PRC.DESCRABREV = :A_VALUE
			AND PROC.STATUSPROC IN :P_STATUSPROC
			AND (PROC.IDIPROC = :P_IDIPROC OR :P_IDIPROC IS NULL)
			AND :P_DETALHAR = 'P'
			AND NVL(PROC.DHTERMINO,TO_DATE('01/01/2099')) = CASE WHEN :P_FINAL='S' THEN NVL(PROC.DHTERMINO,TO_DATE('01/01/2099')) ELSE TO_DATE('01/01/2099') END
		ORDER BY PROC.DTPREVENT, PROC.NROLOTE) PROCESSO
UNION
SELECT * 
FROM (SELECT TV.IDIATV AS CODIGO,
			EFX.DESCRICAO AS DESCRICAO,
			PROC.IDIPROC AS IDIPROC,
			TV.DHINCLUSAO AS DTINICO,
			TV.DHFINAL AS DHFINAL,
			PROC.DTPREVENT,
			PROC.NROLOTE,
			IPA.QTDPRODUZIR AS TAMLOTE,
			IPA.QTDPRODUZIR - NVL((SELECT SUM(APA.QTDAPONTADA+APA.QTDPERDA) FROM TPRAPO APO INNER JOIN TPRAPA APA ON (APO.NUAPO = APA.NUAPO) WHERE APO.SITUACAO='C' AND APO.IDIATV = TV.IDIATV AND TRUNC(APO.DHAPO) BETWEEN :P_DTAPONT.INI AND :P_DTAPONT.FIN),0) AS QTDPRODUZIR,
			NVL((SELECT SUM(APA.QTDAPONTADA) FROM TPRAPO APO INNER JOIN TPRAPA APA ON (APO.NUAPO = APA.NUAPO) WHERE APO.SITUACAO='C' AND APO.IDIATV = TV.IDIATV AND TRUNC(APO.DHAPO) BETWEEN :P_DTAPONT.INI AND :P_DTAPONT.FIN),0) AS QTDAPON,
			NVL((SELECT SUM(APA.QTDPERDA) FROM TPRAPO APO INNER JOIN TPRAPA APA ON (APO.NUAPO = APA.NUAPO) WHERE APO.SITUACAO='C' AND APO.IDIATV = TV.IDIATV AND TRUNC(APO.DHAPO) BETWEEN :P_DTAPONT.INI AND :P_DTAPONT.FIN),0) AS QTDPERDA,
			PRO.CODPROD,
			PRO.DESCRPROD,
			(CASE WHEN PRO.AD_LINHA = 1 THEN 'Linha 1' WHEN PRO.AD_LINHA = 2 THEN 'Linha 2' ELSE 'Linha N/E' END) AS LINHA,
			(SELECT DISTINCT G.DESCRGRUPOPROD FROM TGFGRU G WHERE G.CODGRUPOPROD = PRO.CODGRUPOPROD) AS DESCRGRUPOPROD,
			OPTION_LABEL('TPRIPROC','STATUSPROC',PROC.STATUSPROC) AS STATUSPROD
		FROM TPRIPROC PROC 
			INNER JOIN TPRPRC PRC ON (PROC.IDPROC = PRC.IDPROC)
			INNER JOIN TPRIATV TV ON (TV.IDIPROC = PROC.IDIPROC)
			INNER JOIN TPREFX EFX ON (EFX.IDEFX = TV.IDEFX)
			INNER JOIN TPRIPA IPA ON (IPA.IDIPROC = PROC.IDIPROC)
			INNER JOIN TGFPRO PRO ON (IPA.CODPRODPA = PRO.CODPROD)
		WHERE EFX.DESCRICAO = :A_VALUE
			AND PROC.STATUSPROC IN :P_STATUSPROC
			AND (PROC.IDIPROC = :P_IDIPROC OR :P_IDIPROC IS NULL)
			AND NVL(TV.DHFINAL,TO_DATE('01/01/2099')) = CASE WHEN :P_FINAL='S' THEN NVL(TV.DHFINAL,TO_DATE('01/01/2099')) ELSE TO_DATE('01/01/2099') END
			AND :P_DETALHAR = 'A'
		ORDER BY PROC.DTPREVENT,
		PROC.NROLOTE)