SELECT P.CODPROD,
    P.DESCRPROD,
    P.COMPLDESC,
    P.AD_DESCRPRODOED,
    P.AD_QTDEMB,
    P.REFERENCIA,
    P.NCM,
    P.AD_PESOLIQ_SPARK,
    NVL(TRIM(TO_CHAR(P.AD_ESPESSURA_SPARK)), '0') || 'x' || NVL(TRIM(TO_CHAR(P.AD_LARGURA_SPARK)),   '0') || 'x' || NVL(TRIM(TO_CHAR(P.AD_ALTURA_SPARK)),    '0') AS MEDIDA_PRODUTO,
    P.PESOBRUTO,
    NVL(TRIM(TO_CHAR(P.ESPESSURA)), '0') || 'x' || NVL(TRIM(TO_CHAR(P.LARGURA)),   '0') || 'x' || NVL(TRIM(TO_CHAR(P.ALTURA)),    '0') AS MEDIDA_CAIXA,
    G.CODGRUPOPROD || ' - ' || G.DESCRGRUPOPROD AS DESCRGRUPOPROD
FROM TGFPRO P
    INNER JOIN TGFGRU G ON P.CODGRUPOPROD = G.CODGRUPOPROD
WHERE P.ATIVO = 'S'
    AND NVL(P.AD_OBSOLETO, 'N') <> 'S'
    AND P.CODGRUPOPROD IN (
        SELECT CODGRUPOPROD
            FROM TGFGRU
        WHERE CODGRUPOPROD = :P_CODGRUPOPROD
            OR (    CODGRUPAI = :P_CODGRUPOPROD
                AND (SELECT ANALITICO FROM TGFGRU WHERE CODGRUPOPROD = :P_CODGRUPOPROD) = 'N'
                )
    )
ORDER BY P.DESCRPROD