
  CREATE TABLE "SPARKPRD"."AD_TGSISGM" 
   (	"CODSGRU" NUMBER(10,0) NOT NULL ENABLE, 
	"ANO" NUMBER(10,0) NOT NULL ENABLE, 
	"MES" VARCHAR2(100) NOT NULL ENABLE, 
	"IDGRU" NUMBER(10,0), 
	"TIPO" VARCHAR2(10), 
	"CODGRUPOPROD" NUMBER(10,0), 
	 CONSTRAINT "PK_AD_TGSISGM" PRIMARY KEY ("CODSGRU", "ANO", "MES", "IDGRU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SPARKDADOS"  ENABLE, 
	 CONSTRAINT "AD_FK_8AD3019CAE6E62291D969" FOREIGN KEY ("CODSGRU", "ANO", "MES")
	  REFERENCES "SPARKPRD"."AD_TGSSGM" ("CODSGRU", "ANO", "MES") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SPARKDADOS"