SELECT FUNCREVISOR,
	SUM(DEFEITO) AS DEFEITO,
	CODFUNC
FROM (
	SELECT SUBSTR(CAD.NOMEFUNC, 1, INSTR(CAD.NOMEFUNC, ' ') - 1) AS FUNCREVISOR,
		CAD.CODFUNC,
		(SUM(APO.MINSERIDO) + 
		SUM(APO.FALTANDO) + 
		SUM(APO.INVERTIDO) + 
		SUM(APO.TROCADO) + 
		SUM(APO.QUEIMADO) + 
		SUM(APO.CURTO) + 
		SUM(APO.SOLDAFRIA) + 
		SUM(APO.DEFEITOMP) + 
		SUM(APO.CHICOTE) + 
		SUM(APO.DISPLAY) + 
		SUM(APO.AJUTENSAO) + 
		SUM(APO.ACORRENTE) + 
		SUM(APO.LED) + 
		SUM(APO.CONSUMO) + 
		SUM(APO.CORRENTE) + 
		SUM(APO.PROGRAMACAO) + 
		SUM(APO.OUTROSDEFEITOS) + 
		SUM(APO.ADESIVOTROC) + 
		SUM(APO.ADESIVOTORT) + 
		SUM(APO.GABARRANHADO) + 
		SUM(APO.GABAMASSADO) + 
		SUM(APO.TAMPATROCA) + 
		SUM(APO.TAMPAAMASS)) AS DEFEITO
	FROM AD_APOQLD APO
		INNER JOIN TFPFUN CAD ON APO.FUNCREVISOR2 = CAD.CODFUNC
	WHERE APO.DTAPO >= :P_PERIODO.INI
		AND APO.DTAPO <= :P_PERIODO.FIN
	GROUP BY SUBSTR(CAD.NOMEFUNC, 1, INSTR(CAD.NOMEFUNC, ' ') - 1), CAD.CODFUNC
	)
GROUP BY FUNCREVISOR, CODFUNC
HAVING SUM(DEFEITO) > 0
ORDER BY DEFEITO DESC