SELECT TIPODEFEITO, 
	SUM(QUANTIDADE) AS Total
FROM (
	SELECT 'Mal Inserido' AS TIPODEFEITO, NVL(SUM(APO.MINSERIDO),0) AS QUANTIDADE 
	FROM AD_APOQLD APO
    WHERE (APO.FUNCOPERADOR = :A_IDFUNC OR APO.FUNCOPERADOR2 = :A_IDFUNC OR APO.FUNCREVISOR2 = :A_IDFUNC) AND APO.DTAPO >= :P_PERIODO.INI AND APO.DTAPO <= :P_PERIODO.FIN
	UNION ALL
	SELECT 'Faltando' AS TIPODEFEITO, NVL(SUM(APO.FALTANDO),0) AS QUANTIDADE 
	FROM AD_APOQLD APO
    WHERE (APO.FUNCOPERADOR = :A_IDFUNC OR APO.FUNCOPERADOR2 = :A_IDFUNC OR APO.FUNCREVISOR2 = :A_IDFUNC) AND APO.DTAPO >= :P_PERIODO.INI AND APO.DTAPO <= :P_PERIODO.FIN
	UNION ALL
	SELECT 'Invertido' AS TIPODEFEITO, NVL(SUM(APO.INVERTIDO),0) AS QUANTIDADE 
	FROM AD_APOQLD APO
    WHERE (APO.FUNCOPERADOR = :A_IDFUNC OR APO.FUNCOPERADOR2 = :A_IDFUNC OR APO.FUNCREVISOR2 = :A_IDFUNC) AND APO.DTAPO >= :P_PERIODO.INI AND APO.DTAPO <= :P_PERIODO.FIN
	UNION ALL
	SELECT 'Trocado' AS TIPODEFEITO, NVL(SUM(APO.TROCADO),0) AS QUANTIDADE 
	FROM AD_APOQLD APO
    WHERE (APO.FUNCOPERADOR = :A_IDFUNC OR APO.FUNCOPERADOR2 = :A_IDFUNC OR APO.FUNCREVISOR2 = :A_IDFUNC) AND APO.DTAPO >= :P_PERIODO.INI AND APO.DTAPO <= :P_PERIODO.FIN
	UNION ALL
	SELECT 'Queimado' AS TIPODEFEITO, NVL(SUM(APO.QUEIMADO),0) AS QUANTIDADE 
	FROM AD_APOQLD APO
    WHERE (APO.FUNCOPERADOR = :A_IDFUNC OR APO.FUNCOPERADOR2 = :A_IDFUNC OR APO.FUNCREVISOR2 = :A_IDFUNC) AND APO.DTAPO >= :P_PERIODO.INI AND APO.DTAPO <= :P_PERIODO.FIN
	UNION ALL
	SELECT 'Curto' AS TIPODEFEITO, NVL(SUM(APO.CURTO),0) AS QUANTIDADE 
	FROM AD_APOQLD APO
    WHERE (APO.FUNCOPERADOR = :A_IDFUNC OR APO.FUNCOPERADOR2 = :A_IDFUNC OR APO.FUNCREVISOR2 = :A_IDFUNC) AND APO.DTAPO >= :P_PERIODO.INI AND APO.DTAPO <= :P_PERIODO.FIN
	UNION ALL
	SELECT 'Solda Fria' AS TIPODEFEITO, NVL(SUM(APO.SOLDAFRIA),0) AS QUANTIDADE 
	FROM AD_APOQLD APO
    WHERE (APO.FUNCOPERADOR = :A_IDFUNC OR APO.FUNCOPERADOR2 = :A_IDFUNC OR APO.FUNCREVISOR2 = :A_IDFUNC) AND APO.DTAPO >= :P_PERIODO.INI AND APO.DTAPO <= :P_PERIODO.FIN
	UNION ALL
	SELECT 'Defeito de MP' AS TIPODEFEITO, NVL(SUM(APO.DEFEITOMP),0) AS QUANTIDADE 
	FROM AD_APOQLD APO
    WHERE (APO.FUNCOPERADOR = :A_IDFUNC OR APO.FUNCOPERADOR2 = :A_IDFUNC OR APO.FUNCREVISOR2 = :A_IDFUNC) AND APO.DTAPO >= :P_PERIODO.INI AND APO.DTAPO <= :P_PERIODO.FIN
	UNION ALL
	SELECT 'Chicote' AS TIPODEFEITO, NVL(SUM(APO.CHICOTE),0) AS QUANTIDADE 
	FROM AD_APOQLD APO
    WHERE (APO.FUNCOPERADOR = :A_IDFUNC OR APO.FUNCOPERADOR2 = :A_IDFUNC OR APO.FUNCREVISOR2 = :A_IDFUNC) AND APO.DTAPO >= :P_PERIODO.INI AND APO.DTAPO <= :P_PERIODO.FIN
	UNION ALL
	SELECT 'Display' AS TIPODEFEITO, NVL(SUM(APO.DISPLAY),0) AS QUANTIDADE 
	FROM AD_APOQLD APO
    WHERE (APO.FUNCOPERADOR = :A_IDFUNC OR APO.FUNCOPERADOR2 = :A_IDFUNC OR APO.FUNCREVISOR2 = :A_IDFUNC) AND APO.DTAPO >= :P_PERIODO.INI AND APO.DTAPO <= :P_PERIODO.FIN
	UNION ALL
	SELECT 'Não Ajusta Tensão' AS TIPODEFEITO, NVL(SUM(APO.AJUTENSAO),0) AS QUANTIDADE 
	FROM AD_APOQLD APO
    WHERE (APO.FUNCOPERADOR = :A_IDFUNC OR APO.FUNCOPERADOR2 = :A_IDFUNC OR APO.FUNCREVISOR2 = :A_IDFUNC) AND APO.DTAPO >= :P_PERIODO.INI AND APO.DTAPO <= :P_PERIODO.FIN
	UNION ALL
	SELECT 'Não Ajusta Corrent' AS TIPODEFEITO, NVL(SUM(APO.ACORRENTE),0) AS QUANTIDADE 
	FROM AD_APOQLD APO
    WHERE (APO.FUNCOPERADOR = :A_IDFUNC OR APO.FUNCOPERADOR2 = :A_IDFUNC OR APO.FUNCREVISOR2 = :A_IDFUNC) AND APO.DTAPO >= :P_PERIODO.INI AND APO.DTAPO <= :P_PERIODO.FIN
	UNION ALL
	SELECT 'LED' AS TIPODEFEITO, NVL(SUM(APO.LED),0) AS QUANTIDADE 
	FROM AD_APOQLD APO
    WHERE (APO.FUNCOPERADOR = :A_IDFUNC OR APO.FUNCOPERADOR2 = :A_IDFUNC OR APO.FUNCREVISOR2 = :A_IDFUNC) AND APO.DTAPO >= :P_PERIODO.INI AND APO.DTAPO <= :P_PERIODO.FIN
	UNION ALL
	SELECT 'Consumo' AS TIPODEFEITO, NVL(SUM(APO.CONSUMO),0) AS QUANTIDADE 
	FROM AD_APOQLD APO
    WHERE (APO.FUNCOPERADOR = :A_IDFUNC OR APO.FUNCOPERADOR2 = :A_IDFUNC OR APO.FUNCREVISOR2 = :A_IDFUNC) AND APO.DTAPO >= :P_PERIODO.INI AND APO.DTAPO <= :P_PERIODO.FIN
	UNION ALL
	SELECT 'Corrente Zerada' AS TIPODEFEITO, NVL(SUM(APO.CORRENTE),0) AS QUANTIDADE 
	FROM AD_APOQLD APO
    WHERE (APO.FUNCOPERADOR = :A_IDFUNC OR APO.FUNCOPERADOR2 = :A_IDFUNC OR APO.FUNCREVISOR2 = :A_IDFUNC) AND APO.DTAPO >= :P_PERIODO.INI AND APO.DTAPO <= :P_PERIODO.FIN
	UNION ALL
	SELECT 'Não Programa' AS TIPODEFEITO, NVL(SUM(APO.PROGRAMACAO),0) AS QUANTIDADE 
	FROM AD_APOQLD APO
    WHERE (APO.FUNCOPERADOR = :A_IDFUNC OR APO.FUNCOPERADOR2 = :A_IDFUNC OR APO.FUNCREVISOR2 = :A_IDFUNC) AND APO.DTAPO >= :P_PERIODO.INI AND APO.DTAPO <= :P_PERIODO.FIN
	UNION ALL
	SELECT 'Outros Defeitos' AS TIPODEFEITO, NVL(SUM(APO.OUTROSDEFEITOS),0) AS QUANTIDADE 
	FROM AD_APOQLD APO
    WHERE (APO.FUNCOPERADOR = :A_IDFUNC OR APO.FUNCOPERADOR2 = :A_IDFUNC OR APO.FUNCREVISOR2 = :A_IDFUNC) AND APO.DTAPO >= :P_PERIODO.INI AND APO.DTAPO <= :P_PERIODO.FIN
	UNION ALL
	SELECT 'Adesivo Trocado' AS TIPODEFEITO, NVL(SUM(APO.ADESIVOTROC),0) AS QUANTIDADE 
	FROM AD_APOQLD APO
    WHERE (APO.FUNCOPERADOR = :A_IDFUNC OR APO.FUNCOPERADOR2 = :A_IDFUNC OR APO.FUNCREVISOR2 = :A_IDFUNC) AND APO.DTAPO >= :P_PERIODO.INI AND APO.DTAPO <= :P_PERIODO.FIN
	UNION ALL
	SELECT 'Adesivo Torto' AS TIPODEFEITO, NVL(SUM(APO.ADESIVOTORT),0) AS QUANTIDADE 
	FROM AD_APOQLD APO
    WHERE (APO.FUNCOPERADOR = :A_IDFUNC OR APO.FUNCOPERADOR2 = :A_IDFUNC OR APO.FUNCREVISOR2 = :A_IDFUNC) AND APO.DTAPO >= :P_PERIODO.INI AND APO.DTAPO <= :P_PERIODO.FIN
	UNION ALL
	SELECT 'Gabinete Arranhado' AS TIPODEFEITO, NVL(SUM(APO.GABARRANHADO),0) AS QUANTIDADE 
	FROM AD_APOQLD APO
    WHERE (APO.FUNCOPERADOR = :A_IDFUNC OR APO.FUNCOPERADOR2 = :A_IDFUNC OR APO.FUNCREVISOR2 = :A_IDFUNC) AND APO.DTAPO >= :P_PERIODO.INI AND APO.DTAPO <= :P_PERIODO.FIN
	UNION ALL
	SELECT 'Gabinete Amassado' AS TIPODEFEITO, NVL(SUM(APO.GABAMASSADO),0) AS QUANTIDADE 
	FROM AD_APOQLD APO
    WHERE (APO.FUNCOPERADOR = :A_IDFUNC OR APO.FUNCOPERADOR2 = :A_IDFUNC OR APO.FUNCREVISOR2 = :A_IDFUNC) AND APO.DTAPO >= :P_PERIODO.INI AND APO.DTAPO <= :P_PERIODO.FIN
	UNION ALL
	SELECT 'Tampa Trocada' AS TIPODEFEITO, NVL(SUM(APO.TAMPATROCA),0) AS QUANTIDADE 
	FROM AD_APOQLD APO
    WHERE (APO.FUNCOPERADOR = :A_IDFUNC OR APO.FUNCOPERADOR2 = :A_IDFUNC OR APO.FUNCREVISOR2 = :A_IDFUNC) AND APO.DTAPO >= :P_PERIODO.INI AND APO.DTAPO <= :P_PERIODO.FIN
	UNION ALL
	SELECT 'Tampa Amassada' AS TIPODEFEITO, NVL(SUM(APO.TAMPAAMASS),0) AS QUANTIDADE 
	FROM AD_APOQLD APO
    WHERE (APO.FUNCOPERADOR = :A_IDFUNC OR APO.FUNCOPERADOR2 = :A_IDFUNC OR APO.FUNCREVISOR2 = :A_IDFUNC) AND APO.DTAPO >= :P_PERIODO.INI AND APO.DTAPO <= :P_PERIODO.FIN) DEFEITOS
GROUP BY TIPODEFEITO
HAVING SUM(QUANTIDADE) > 0