SELECT FIN.NUFIN,
	FIN.CODEMP,
	FIN.CODPARC,
	PAR.NOMEPARC,
    FIN.NUCOMPENS,
	FIN.NUMNOTA,
	FIN.VLRDESDOB,
	FIN.DTNEG,
	FIN.HISTORICO,
	NAT.DESCRNAT,
	FIN.CODUSU||' - '|| USU.NOMEUSU AS USUARIO,
    (CASE WHEN FIN.RECDESP = 1 THEN 'RECEITA' ELSE 'DESPESA' END) AS RECDESP
FROM TGFFIN FIN	
	INNER JOIN TGFPAR PAR ON PAR.CODPARC = FIN.CODPARC
	INNER JOIN TGFNAT NAT ON NAT.CODNAT = FIN.CODNAT
    INNER JOIN TSIUSU USU ON USU.CODUSU = FIN.CODUSU
    INNER JOIN TGFFRE FRE ON FIN.NUCOMPENS = FRE.NUACERTO
WHERE FIN.NUCOMPENS = :A_NUCOMPENS