SELECT PRO.AD_AGRUPADOR,
	PRO.CODVOL,
	SUM(ITE.QTDNEG) AS QTD,
	PRO.CODGRUPOPROD,
	GRU.DESCRGRUPOPROD,
	VEN.CODVEND,
	VEN.APELIDO,
	(SUM(ITE.QTDNEG)/(SELECT SUM(ITE2.QTDNEG) AS TOTALF
						FROM TGFITE ITE2
						INNER JOIN TGFCAB CAB2 ON ITE2.NUNOTA = CAB2.NUNOTA
						INNER JOIN TGFPRO PRO2 ON ITE2.CODPROD = PRO2.CODPROD
						INNER JOIN TGFGRU GRU2 ON PRO2.CODGRUPOPROD = GRU2.CODGRUPOPROD
						INNER JOIN TGFVEN VEN2 ON CAB2.CODVEND = VEN2.CODVEND
						WHERE TRUNC(CAB2.DTNEG) >= :P_PER.INI AND TRUNC(CAB2.DTNEG) <= :P_PER.FIN AND CAB2.TIPMOV = 'D' AND PRO2.USOPROD = 'V' AND ((GRU2.CODGRUPOPROD = :P_GRUPO) OR :P_GRUPO IS NULL) AND ((:P_CODEMP IS NULL) OR (CAB2.CODEMP = :P_CODEMP)) AND ((:P_CODVEND IS NULL) OR (VEN2.CODVEND = :P_CODVEND)) AND CAB2.CODTIPOPER IN (1200,1201,1206,1216,1217,1272))) * 100 AS PARTE,
	SUM(ITE.VLRTOT - ITE.VLRDESC) AS TOTALLIQ,
	SUM(NVL(ITE.AD_VLROUTROS,0)) AS TOTALOUTROS,
	SUM(ITE.VLRTOT - ITE.VLRDESC) + SUM(NVL(ITE.AD_VLROUTROS,0)) AS TOTAL,
	((SUM(ITE.VLRTOT - ITE.VLRDESC) + SUM(NVL(ITE.AD_VLROUTROS,0)))/(SELECT SUM(ITE3.VLRTOT - ITE3.VLRDESC) + SUM(NVL(ITE3.AD_VLROUTROS,0)) AS TOTALFAT
																					FROM TGFITE ITE3
																					INNER JOIN TGFCAB CAB3 ON ITE3.NUNOTA = CAB3.NUNOTA
																					INNER JOIN TGFPRO PRO3 ON ITE3.CODPROD = PRO3.CODPROD
																					INNER JOIN TGFGRU GRU3 ON PRO3.CODGRUPOPROD = GRU3.CODGRUPOPROD
																					INNER JOIN TGFVEN VEN3 ON CAB3.CODVEND = VEN3.CODVEND
																					WHERE TRUNC(CAB3.DTNEG) >= :P_PER.INI AND TRUNC(CAB3.DTNEG) <= :P_PER.FIN AND CAB3.TIPMOV = 'D' AND PRO3.USOPROD = 'V' AND ((GRU3.CODGRUPOPROD = :P_GRUPO) OR :P_GRUPO IS NULL) AND ((:P_CODEMP IS NULL) OR (CAB3.CODEMP = :P_CODEMP)) AND ((:P_CODVEND IS NULL) OR (VEN3.CODVEND = :P_CODVEND)) AND CAB3.CODTIPOPER IN (1200,1201,1206,1216,1217,1272))) * 100 AS PARTEFATURADO
FROM TGFITE ITE
	INNER JOIN TGFCAB CAB ON ITE.NUNOTA = CAB.NUNOTA
	INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
	INNER JOIN TGFGRU GRU ON PRO.CODGRUPOPROD = GRU.CODGRUPOPROD
	INNER JOIN TGFVEN VEN ON CAB.CODVEND = VEN.CODVEND
	INNER JOIN TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC
	INNER JOIN TSICID CID ON PAR.CODCID = CID.CODCID
WHERE TRUNC(CAB.DTNEG) >= :P_PER.INI 
	AND TRUNC(CAB.DTNEG) <= :P_PER.FIN 
	AND CAB.TIPMOV = 'D' 
	AND PRO.USOPROD = 'V' 
	AND ((GRU.CODGRUPOPROD = :P_GRUPO) OR :P_GRUPO IS NULL) 
	AND ((:P_CODEMP IS NULL) OR (CAB.CODEMP = :P_CODEMP)) 
	AND ((:P_CODVEND IS NULL) OR (VEN.CODVEND = :P_CODVEND)) 
	AND CAB.CODTIPOPER IN (1200,1201,1206,1216,1217,1272) 
	AND ((:P_CODPROD IS NULL) OR (ITE.CODPROD = :P_CODPROD)) 
	AND ((:P_CODPARC IS NULL OR CAB.CODPARC = :P_CODPARC) AND (:P_CODPARCMATRIZ IS NULL OR PAR.CODPARCMATRIZ = :P_CODPARCMATRIZ))
	AND (:P_CODUF IS NULL OR CID.UF = :P_CODUF)
GROUP BY PRO.AD_AGRUPADOR, PRO.CODVOL, PRO.CODGRUPOPROD, GRU.DESCRGRUPOPROD, VEN.CODVEND, VEN.APELIDO
ORDER BY PRO.AD_AGRUPADOR