SELECT COUNT(ASS.NUMOS) AS QTD,
    PRO.AD_AGRUPADOR AS DESCRPROD
    
FROM AD_TGFASS ASS
    LEFT JOIN TGFPRO PRO ON ASS.T_CODPROD = PRO.CODPROD
WHERE ASS.DTRECEB BETWEEN :P_PERIODO.INI AND :P_PERIODO.FIN
    AND (:P_DTFAB.INI IS NULL OR TRUNC(ASS.T_DTFABRICACAO) >= :P_DTFAB.INI)
    AND (:P_DTFAB.FIN IS NULL OR TRUNC(ASS.T_DTFABRICACAO) <= :P_DTFAB.FIN)
GROUP BY PRO.AD_AGRUPADOR
ORDER BY COUNT(ASS.NUMOS) DESC