CREATE OR REPLACE VIEW VGF_ESTOQUEMELI_SPARK AS
SELECT
    CODPROD,
    CODLOCAL,
    CODEMP,
    SUM(CASE 
            WHEN ESTOQUE < 0 THEN 0
            ELSE ESTOQUE
        END) AS ESTOQUE
FROM TGFEST
WHERE CODEMP = 1
  AND CODPROD IN (
      SELECT CODPROD 
      FROM AD_MKTPMELI 
      WHERE ACTIVE = 'active'
  )
GROUP BY CODPROD, CODLOCAL;