CREATE OR REPLACE VIEW VGFEST (SKU, ESTO) AS
SELECT PRO.CODPROD AS SKU
	,NVL(ESTOQUE, 0) AS ESTO
FROM TGFPRO PRO
LEFT OUTER JOIN (
	SELECT CODPROD
		,SUM(ESTOQUE) ESTOQUE
	FROM TGFEST
	WHERE CODEMP IN (1)
		AND CODLOCAL IN (109)
	GROUP BY CODPROD
	) EST ON (EST.CODPROD = PRO.CODPROD)
WHERE PRO.ATIVO = 'S'
	AND PRO.CODPROD IN (
		SELECT DISTINCT ITE.CODPROD
		FROM TGFCAB CAB
		JOIN TGFITE ITE ON ITE.NUNOTA = CAB.NUNOTA
		WHERE DTNEG > SYSDATE - 300
		)
	AND PRO.USOPROD IN (
		'R'
		,'V'
		)
GROUP BY PRO.CODPROD
	,NVL(ESTOQUE, 0)

UNION ALL

SELECT A.CODPROD AS SKU
	,NVL(MIN(VALOR), 0) AS ESTO
FROM (
	SELECT ICP.CODPROD
		,CASE 
			WHEN SUM(ESTOQUE) < 0
				THEN 0
			ELSE SUM(ESTOQUE)
			END AS VALOR
		,ICP.CODMATPRIMA
	FROM TGFICP ICP
	INNER JOIN TGFEST EST ON EST.CODPROD = ICP.CODMATPRIMA
	WHERE EST.CODEMP IN (1)
		AND EST.CODLOCAL IN (109)
	GROUP BY ICP.CODPROD
		,CODMATPRIMA
	
	UNION ALL
	
	SELECT CODPROD
		,0 AS VALOR
		,CODMATPRIMA
	FROM TGFICP
	WHERE codmatprima NOT IN (
			SELECT ICP.CODMATPRIMA
			FROM TGFICP ICP
			JOIN TGFEST EST ON EST.CODPROD = ICP.CODMATPRIMA
			WHERE EST.CODEMP IN (1)
				AND EST.CODLOCAL IN (109)
			)
	) A
GROUP BY A.CODPROD
;